BasedHardware/omi

src/BluetoothDeviceDriver/BluetoothDeviceDriver.ino
Implemented the double tap to start/stop recording. Re-format some code.
requires the lib `Seeed arduino LSM6DS3`
=> feat: Implement double tap start recording

AppWithWearable/android/app/src/main/AndroidManifest.xml, AppWithWearable/android/build.gradle, AppWithWearable/lib/custom_code/actions/ble0find_devices.dart
=> fix: Fix device search for Android

AppWithWearable/ios/Runner/Info.plist
This should fix background processing.
=> Added Background Permission for IOS

.gitignore, apps/AppWithWearable/lib/components/items/item_permission/item_permission_widget.dart
=> Fixed App permissions to BLE and Notifications

README.md
Tested the prior wires and they are too big and ordered these ones instead
=> Update to 26 gauge wires 18 gauge is way too thick

README.md
Reverts BasedHardware/Friend#45
=> Revert "Update README.md with Latest Design with LiPo Battery"

apps/AppWithWearable/lib/custom_code/actions/ble_receive_w_a_v.dart, apps/AppWithWearable/lib/custom_code/actions/stream_api_response.dart, apps/AppWithWearable/lib/pages/ble/find_devices/find_devices_widget.dart, apps/AppWithWearable/lib/pages/connect_device/connect_device_widget.dart
=> Settings Panel

apps/AppWithWearable/ios/Runner.xcodeproj/project.pbxproj, apps/AppWithWearable/lib/main.dart
By mistake sentry logger was uploading all console logs
=> sentry debug options to false

docs/_get_started/Setup.md
I am making this pull request to help the readability of this document.
Please see the attached screenshots for before and after.
**Before**
**After**
I have tested locally to ensure that there are no breaking changes to the page.
=> Making a proposal for readability

.gitignore
add userdata dir, vscode configs, and recordings output to ignored files
=> [chore] add unneeded files to gitignore

apps/AppWithWearable/lib/backend/storage/memories.dart, apps/AppWithWearable/lib/pages/memory_detail/page.dart
Works and tested on android, allows users to edit the Action Items list.
=> Add edit action items

apps/AppWithWearable/README.md, apps/AppWithWearable/initialsetup.bash
The app build Readme doesn't work for me, I was told it is probably broken. I added a couple of steps and asking for help to fix it further
=> Fixes and todos for app readme

apps/AppWithWearable/lib/pages/home/page.dart
https://github.com/orgs/BasedHardware/projects/1/views/1?pane=issue&itemId=68077365
=> Disabled battery bar when device is disconnected

apps/AppWithWearable/lib/pages/backup/page.dart, apps/AppWithWearable/lib/pages/settings/developer.dart
Fixes some grammatical errors in the copy text of the app.
=> Fix some typos

apps/AppWithWearable/lib/pages/onboarding/wrapper.dart, apps/AppWithWearable/lib/widgets/device_widget.dart
=> Fix Get Started button not visible on Small Screens

apps/AppWithWearable/lib/pages/memory_detail/page.dart, apps/AppWithWearable/lib/pages/onboarding/setup/setup_questions.dart, apps/AppWithWearable/lib/pages/settings/page.dart, apps/AppWithWearable/lib/pages/settings/privacy.dart, apps/AppWithWearable/lib/pages/speaker_id/page.dart
...I didn't see any issue with text fields? this works well for me.
Please explain what would be the issue.
=> Fix iOS native swipe issues

apps/AppWithWearable/lib/pages/settings/page.dart
=> Fix analytics toggle

docs/_assembly/Build_the_device.md
I made a little video to easier explain how the Friend AI necklace is assembled. Since GH only allows uploads till 10MB, I had to compress it down and cut it into 2 parts.
=> Add assembly video to assembly guide

apps/AppWithWearable/lib/backend/auth.dart, apps/AppWithWearable/lib/pages/onboarding/wrapper.dart
Fixes #456 
https://github.com/user-attachments/assets/34c5aef8-5bbf-4700-b71f-99ac597c493d
=> Skip Auth if user is already Signed In

apps/AppWithWearable/lib/pages/onboarding/find_device/page.dart
This PR adds the ability to request for Bluetooth permission on Android if it isn't already enabled
https://discord.com/channels/1192313062041067520/1261819368954789888/1264927769670844496
=> Request for bluetooth permission on android if it isn't enabled

firmware/firmware_v1.0/src/main.c, firmware/firmware_v1.0/src/transport.c, firmware/readme.md
Red - when device is not connected to the app.
Blue - when device is connected to the app.
https://github.com/user-attachments/assets/91bd37ac-b8d1-4e65-9ab4-c1e5c86beb53
=> Fixing LED state

apps/AppWithWearable/lib/pages/capture/background_service.dart, apps/AppWithWearable/lib/pages/capture/logic/websocket_mixin.dart, apps/AppWithWearable/lib/pages/capture/page.dart, apps/AppWithWearable/lib/pages/capture/phone_recorder_mixin.dart, apps/AppWithWearable/lib/utils/websockets.dart, apps/AppWithWearable/pubspec.yaml, community-plugins.json
This PR adds the ability to record audio from microphone in the form of a stream of bytes which are then sent over to websocket. While mobile devices support both pcm8 and pcm16, the latter is being used because of better audio quality.
Codec: pcm16
Channels: 1
Sample Rate: 16000Hz
=> Stream microphone recordings over websocket

plugins/mem0/README.md
This PR adds a readme which explains how mem0 can be used with Friend. It should be merged after PR #479
=> feat: Add mem0 readme

plugins/example/_mem0/router.py
Fixes the issue of search API erroring out due to bad input type.
=> [Mem0] Fix search API call related issue

app/lib/backend/database/memory.dart, app/lib/backend/database/transcript_segment.dart, app/lib/pages/memory_detail/widgets.dart, app/lib/pages/plugins/plugin_detail.dart, app/lib/widgets/transcript.dart
Continuation of #486 
Should close #480 and #434
=> Fix non-english characters rendering

app/android/app/src/main/AndroidManifest.xml, app/lib/pages/capture/location_service.dart, app/lib/pages/capture/page.dart
---
- New Feature: Added support for background location tracking to enhance app functionality when not in active use.
- Improvement: Enhanced the device's location retrieval process, providing more accurate and reliable data.
- New Feature: Implemented permission requests for accessing user's location in the background, improving transparency and user control over privacy settings.
- Improvement: Improved error handling for location services, ensuring a smoother user experience and better troubleshooting capabilities.
=> Android Background Location Fixes

community-plugins.json
=> Creator name change for Warren Buffett plugin

Friend/firmware/readme.md, Friend/hardware/triangle v2 w memory/README.md, README.md, docs/_assembly/Build_the_device.md, docs/_assembly/Buying_Guide.md, docs/_assembly/Install_firmware.md, docs/_config.yml, docs/_developer/Contribution.md, docs/_developer/plugins/Integrations.md, docs/_developer/plugins/Introduction.md, docs/_developer/plugins/Submitting.md, docs/_hardware/DevKit1.md, docs/_hardware/DevKit2.md, docs/_hardware/OpenGlass.md, docs/_info/archive/launch.md, docs/index.md, docs/readme.md, plugins/example/advanced/README.md
Use the new repo URL
Added section about the different devices
Fixed the Friend DevKit 1 shopping guide links
=> Updating the docs

app/lib/pages/home/device_settings.dart, app/lib/pages/home/firmware_mixin.dart, app/lib/pages/home/firmware_update.dart, app/lib/pages/home/support.dart, backend/routers/firmware.py
Every firmware related release should include the following:
- The below keys in the description:
device_type will be 1 for friend and 2 for openglass
```
```
- The tag name should consist of the word `firmware`
- Either the tag name or the release name should consists of the name of the device for which the firmware is. 
Example: `friend`, or `openglass`
- The file/asset which is meant to be used for OTA should contain the word `ota` to distinguish it from other assets
=> OTA Improvements

app/lib/pages/capture/connect.dart, app/lib/pages/capture/logic/phone_recorder_mixin.dart, app/lib/pages/home/device.dart, app/lib/pages/home/device_settings.dart, app/lib/pages/home/firmware_update.dart, app/lib/pages/home/support.dart
- New Feature: Added navigation to `DeviceSettings` from the app bar in `connect.dart` and `device.dart`.
- Refactor: Updated UI rendering logic in `DeviceSettings` based on device connection status for improved user experience.
- Bug Fix: Removed unnecessary WebSocket channel closure in `phone_recorder_mixin.dart` to enhance WebSocket handling.
- Style: Updated text related to firmware updates in `firmware_update.dart` for better user understanding.
- New Feature: Introduced a custom dialog widget in `support.dart` to replace direct URL launches, improving user interaction.
=> OTA and Microphone Improvements 

app/lib/backend/preferences.dart, app/lib/backend/schema/message.dart, app/lib/pages/capture/page.dart, app/lib/pages/capture/widgets/widgets.dart, app/lib/pages/chat/page.dart, app/lib/pages/chat/widgets/ai_message.dart, app/lib/pages/home/firmware_mixin.dart, app/lib/pages/home/page.dart, app/lib/pages/memory_detail/widgets.dart, app/lib/utils/connectivity_controller.dart
=> Better no internet connection states

Friend/hardware/triangle v2 w memory/README.md
Current link 404s. This commit updates the link to a working product page.
=> Update component link

app/lib/pages/chat/widgets/ai_message.dart, app/lib/pages/home/page.dart, app/lib/pages/memory_detail/widgets.dart, app/lib/pages/plugins/page.dart, app/lib/pages/plugins/plugin_detail.dart
Resolved some issues and implemented suggested improvements shared on Discord
=> No Internet State Improvements

app/lib/backend/preferences.dart, app/lib/pages/home/page.dart, app/lib/pages/settings/calendar.dart, app/lib/utils/features/calendar.dart
- New Feature: Enhanced calendar permission management in the settings. Users will now be prompted for calendar access and permissions, improving the overall user experience.
- Bug Fix: Improved handling of internet connection banners on the home page. Banners will now display more accurately based on the connection status and provide smoother dismissal actions.
- Refactor: Optimized initialization of memories and messages, resulting in a more responsive application startup.
=> Fix Calendar permission and Internet banner auto dismiss

app/lib/backend/preferences.dart, app/lib/pages/capture/page.dart, app/lib/pages/capture/widgets/widgets.dart, app/lib/pages/home/device.dart, app/lib/pages/home/device_settings.dart, app/lib/pages/home/page.dart, app/lib/pages/onboarding/find_device/found_devices.dart, app/lib/pages/onboarding/find_device/page.dart, app/lib/utils/ble/connected.dart, app/lib/utils/ble/scan.dart
Related to #596 
- Refactor: Updated the storage and retrieval mechanism of `BTDeviceStruct` object in `SharedPreferencesUtil`. This change enhances the application's ability to handle Bluetooth device information.
- Bug Fix: Improved Flutter connection handling and state management across various pages. This includes checks before calling `setState` to prevent errors and a more robust approach to showing SnackBar messages when memory creation fails.
- New Feature: Added a connection listener on the found devices page, improving the user experience by providing real-time updates about the connection status.
=> Fix known Flutter connection and setState issues

.gitignore, app/android/key.properties
Delete the file app/android/key.properties that contains sensitive data and add the appropriate .gitignore line.
=> Delete key.properties and fix gitignore

community-plugins.json
=> Adding EchoSense to community plugins.

app/lib/main.dart, app/lib/providers/home_provider.dart, app/pubspec.yaml
- New Feature: Introduced a `HomeProvider` for managing home page state using the `provider` package.
- Refactor: Updated the application to use `MultiProvider` for better state management and code organization.
- Style: Set the default `themeMode` to dark and made some theme configuration updates.
- New Feature: Implemented conditional rendering of the home page based on onboarding completion and user authentication status. 
- New Feature: Added counter functionality in the `HomeProvider` with an increment method, enhancing interactivity on the home page.
=> provider basic setup

app/android/app/build.gradle, app/pubspec.yaml, codemagic.yaml
Issue: https://github.com/BasedHardware/Omi/issues/525
Use Codemagic on CI/CD, target iOS/Android
- Chore: Updated Android signing configuration to support Codemagic CI/CD. This change allows for seamless integration and deployment using Codemagic's environment.
- Refactor: Set the `ndkVersion` to "27.0.12077973" for Android NDK. This ensures consistency in the build process across different environments, leading to more reliable builds.
=> Finish setting up codemagic

codemagic.yaml
PR: https://github.com/BasedHardware/Omi/issues/667
Support patch for android and ios via codemagic, integrate with shorebird.
Relates: https://github.com/BasedHardware/Omi/pull/666
=> Updates: Support patch shorebird with codemagic

plugins/example/models.py, plugins/example/zapier/memory_created.py, plugins/example/zapier/models.py
Issue: https://github.com/BasedHardware/Omi/issues/677
- New Feature: Enhanced the `TranscriptSegment` class to improve handling and display of timestamps in transcript segments.
- New Feature: Introduced a `transcript` field during memory creation, enriching the data available for each memory.
- Refactor: Adjusted the `get_trigger_memory_sample` and `create_zapier_memory` functions to include the new `transcript` field.
- Refactor: Updated the `ZapierCreateMemory` class to accommodate the new `transcript` string type field.
- Bug Fix: Removed an unnecessary line of code that was closing the websocket connection in an exception block, improving overall stability.
=> Tzfocqjo omi zapier 677

docs/_get_started/backend_deepdive.md
This pull request adds a comprehensive backend documentation file (`backend_deepdive.md`) for the Omi app. This document serves as a detailed guide for developers and enthusiasts to understand Omi's backend structure and functionality.
- Overview of the Omi ecosystem
- System architecture diagram with color-coded components
- Detailed flow of information from user interaction to memory creation
- In-depth explanations of core components:
- database/memories.py
- database/vector_db.py
- utils/llm.py
- utils/other/storage.py
- database/redis_db.py
- routers/transcribe.py
- Information on contributing and support
This documentation aims to:
1. Provide a clear understanding of Omi's backend architecture
2. Assist new developers in onboarding and understanding the system
3. Serve as a …
=> Add Backend Deep Dive Documentation

app/lib/main.dart, app/lib/pages/plugins/page.dart, app/lib/pages/speaker_id/page.dart, app/lib/providers/capture_provider.dart, app/lib/providers/device_provider.dart, app/lib/providers/onboarding_provider.dart, app/lib/providers/speech_profile_provider.dart
- Infinite loading on onboarding
- Lost frame after using speech profile
- Minor fixes
=> Device infinite loading on onboarding and other fixes

app/lib/pages/settings/page.dart, app/lib/providers/capture_provider.dart, app/lib/providers/device_provider.dart
---
- New Feature: Added a mechanism to track and manage the connection status of audio bytes in the `CaptureProvider` class. This will improve the reliability of audio streaming.
- Bug Fix: Ensured proper cancellation of existing Bluetooth Low Energy (BLE) byte streams before initiating new ones, preventing potential stream conflicts.
- Refactor: Updated URLs for privacy policy and about pages in the `_SettingsPageState` class for better user information access.
- Chore: Included additional safety checks in the `DeviceProvider` class to ensure audio bytes are correctly disconnected when necessary.
---
=> Lost frame issue and other fixes

.github/workflows/frontend_deploy.yml, .gitignore, frontend/.prettierignore, frontend/Dockerfile, frontend/next-env.d.ts, frontend/next.config.mjs, frontend/package-lock.json, frontend/package.json, frontend/sitemap.ts, frontend/src/actions/memories/get-public-memories-prerender.ts, frontend/src/actions/memories/get-public-memories.ts, frontend/src/actions/memories/get-shared-memory.ts, frontend/src/app/layout.tsx, frontend/src/app/memories/[id]/page.tsx, frontend/src/app/memories/layout.tsx, frontend/src/app/page.tsx, frontend/src/components/memories/memory.tsx, frontend/src/components/memories/sumary.tsx, frontend/src/components/memories/tabs.tsx, frontend/src/components/memories/transcript/transcription.tsx, frontend/src/components/shared/app-header.tsx, frontend/src/components/shared/footer.tsx, frontend/src/constants/envConfig.ts
**Release Notes:**
- New Feature: Added GitHub Actions workflow for building and deploying to Cloud Run.
- New Feature: Introduced Docker setup for a Node.js environment optimized for Next.js applications.
- Refactor: Updated layout components including `AppHeader`, `RootLayout`, `MemoriesLayout`, and `Footer` for improved user interface.
- New Feature: Enhanced the Memories component with conditional rendering based on memory content availability.
- Refactor: Renamed `getMemory` function to `getSharedMemory` and updated its usage across the application.
- New Feature: Added new functions `getPublicMemoriesPrerender` and `getPublicMemories` for retrieving public memories.
- New Feature: Implemented sitemap generation based on public memories.
- Refactor: Updated environment configuration …
=> Feature: share memories - initial config deployment

frontend/Dockerfile, frontend/src/components/memories/external-data/external-data.tsx, frontend/src/components/memories/memory.tsx, frontend/src/components/memories/transcript/transcription.tsx, frontend/src/types/memory.types.ts
- Implement external data
- fix/test again dockerfile paths
- New Feature: Introduced a new `ExternalData` component in the frontend. This allows users to view and copy external data associated with memories directly from the UI.
- Update: Enhanced the `Memory` and `Transcription` components to support the rendering of the `ExternalData` component based on the presence of `transcript` and `externalData`.
- Refactor: Adjusted Dockerfile paths and optimized the dependency installation process for improved build performance.
- Update: Expanded the data structure with new interfaces `ExternalData` and `TimestampRange` to handle external data more effectively.
=> Show external data - Fix dockerfile paths

app/lib/services/notification_service.dart, app/lib/widgets/transcript.dart
- Bug Fix: Enhanced security in the notification service by adding a check for the current user before saving the FCM token to the server.
- New Feature: Introduced a function `tryDecodingText` in the transcript widget that improves text display by attempting to decode input text using UTF-8 encoding. If unsuccessful, it will display the original text. This ensures better compatibility with various text formats and enhances user experience.
=> Auth fix maybe

app/lib/backend/auth.dart, app/lib/pages/chat/page.dart, app/lib/pages/memory_detail/page.dart, app/lib/pages/onboarding/find_device/page.dart, app/lib/pages/onboarding/memory_created_widget.dart, app/lib/pages/onboarding/name/name_widget.dart, app/lib/pages/onboarding/speech_profile_widget.dart, app/lib/pages/onboarding/welcome/page.dart, app/lib/pages/onboarding/wrapper.dart, app/lib/pages/settings/page.dart, app/lib/pages/settings/personal_details.dart, app/lib/providers/capture_provider.dart, app/lib/services/notification_service.dart, app/pubspec.yaml
Also fixes #683 
- New Feature: Enhanced user experience in the settings page by introducing a modal bottom sheet for 'Personal Details'.
- Refactor: Updated user's display name update function and field label from "Full Name" to "Given Name".
- New Feature: Improved onboarding process with better navigation, UI updates, and handling of Bluetooth permissions.
- Bug Fix: Fixed issues related to Firebase Cloud Messaging (FCM) and Apple Push Notification Service (APNS) token handling based on the platform.
- Refactor: Optimized scrolling behavior in chat for a smoother user experience.
=> Onboarding improvements and other fixes

app/lib/backend/auth.dart, app/lib/backend/http/api/memories.dart, app/lib/pages/capture/page.dart, app/lib/pages/memories/widgets/memory_list_item.dart, app/lib/pages/memory_detail/page.dart, app/lib/pages/onboarding/memory_created_widget.dart, app/lib/providers/speech_profile_provider.dart, app/lib/utils/memories/process.dart, app/pubspec.yaml
- New Feature: Introduced a new field `isFromOnboarding` to distinguish if the memory is created during onboarding. This change enhances the user experience by providing context-specific functionalities.
- Refactor: Improved the handling of `familyName` in the authentication process, ensuring more accurate data representation.
- Style: Updated the dialog text for enabling location services, making it more concise and clear.
- Chore: Optimized code by removing unnecessary imports and adjusting function parameters for better maintainability.
=> Onboarding and other Fixes

app/lib/main.dart, app/lib/pages/memories/page.dart, app/lib/pages/memory_detail/page.dart, app/lib/pages/onboarding/permissions/notification_permission.dart, app/lib/providers/capture_provider.dart, app/lib/providers/memory_provider.dart, app/lib/providers/onboarding_provider.dart, app/lib/providers/speech_profile_provider.dart, app/lib/services/notification_service.dart
- Memories empty for a sec glitch fix
- Clear transcripts after onboarding speech profile is done
- Better handle bluetooth permission when skipped in onboarding
- Fix bluetooth permission being asked as soon as the app is opened
- Fix notification toggle not working on first try
- New Feature: Added a function to clear transcripts in the CaptureProvider class, improving memory management.
- Bug Fix: Fixed issues with Bluetooth and notification permissions handling during onboarding, enhancing user experience.
- Refactor: Streamlined navigation logic in memory detail page, improving code maintainability.
- Refactor: Optimized MemoryProvider class by introducing new methods for memory initialization and retrying failed memories.
- Bug Fix: Removed redundant checks for notification …
=> Onboarding and other bug fixes

frontend/src/actions/memories/get-shared-memory.ts, frontend/src/app/memories/[id]/loading.tsx, frontend/src/app/memories/[id]/page.tsx, frontend/src/components/memories/transcript/transcription-segment.tsx, frontend/src/components/plugins/indentify-plugin.tsx
- Refactor: Updated the caching mechanism in `getSharedMemory` and `generateMetadata` functions for improved data freshness.
- Chore: Cleaned up unused code in `LoadingMemory` component, enhancing readability and maintainability.
- New Feature: Enhanced user experience in `transcription-segment.tsx` by adding conditional rendering to display different icons based on user status. The speaker label now shows "Owner" if the segment belongs to the user.
- Style: Improved UI in `indentify-plugin.tsx` with adjusted text size and margin for plugin descriptions, providing a cleaner and more intuitive interface.
=> Frontend - UI improvements, remove caching

app/lib/backend/auth.dart, app/lib/backend/http/api/users.dart, app/lib/backend/http/webhooks.dart, app/lib/backend/preferences.dart, app/lib/main.dart, app/lib/pages/settings/page.dart, app/lib/providers/onboarding_provider.dart, app/lib/utils/analytics/mixpanel.dart, backend/routers/users.py
- Delete account (Initial)
- Sign Out
- Add notification and location entries to mixpanel
- New Feature: Added the ability for users to delete their accounts from the settings page.
- New Feature: Enhanced notification and location settings management using SharedPreferencesUtil.
- New Feature: Integrated user properties for notifications and location in Mixpanel analytics.
- Refactor: Updated `signOut` function signature for improved usage and integrated it with backend services.
- Refactor: Improved handling of different status codes in `triggerTranscriptSegmentsRequest`.
- Refactor: Optimized home assignment in `_MyAppState` to use a new `AuthWrapper` widget for better user authentication and onboarding process.
- Bug Fix: Improved error handling in account deletion and user data …
=> Delete account and other minor improvements

frontend/public/sitemap.xml, frontend/sitemap.ts, frontend/src/actions/memories/get-public-memories-prerender.ts, frontend/src/actions/memories/get-public-memories.ts, frontend/src/actions/memories/get-shared-memory.ts, frontend/src/app/memories/[id]/page.tsx, frontend/src/app/robots.ts, frontend/src/components/memories/plugins/plugins.tsx, frontend/src/components/memories/transcript/transcription-segment.tsx, frontend/src/constants/envConfig.ts
- Refactor: Updated the sitemap configuration for better SEO, including changes to URL priorities and the API URL used in sitemap generation.
- New Feature: Enhanced the memory fetching functionality with pagination support, allowing for more efficient data retrieval.
- Style: Adjusted the JSX structure and class names of certain components for improved visual presentation.
=> Updating url app for sitemap

app/lib/pages/memory_detail/widgets.dart, app/pubspec.yaml
```
- Refactor: Improved the code structure within the `showOptionsBottomSheet` function in `app/lib/pages/memory_detail/widgets.dart`. This change enhances the readability and maintainability of the code, leading to more efficient future updates. The user experience remains unaffected by this internal update.
```
=> Share sheet grey screen fix

frontend/src/components/memories/plugins/plugins.tsx, frontend/src/components/memories/summary/sumary.tsx, frontend/src/components/plugins/identify-plugin-loader.tsx, frontend/src/components/plugins/indentify-plugin.tsx, frontend/src/components/shared/gleap.tsx
Fixing this errors related to server components insider client components
- Refactor: Enhanced the `IdentifyPlugin` component to handle loading states and error components, improving user experience during data retrieval.
- Style: Adjusted the styling attributes of certain components for better visual consistency.
- Chore: Cleaned up redundant empty lines in the code for improved readability and maintainability.
- Refactor: Updated the rendering location of the `Plugins` component in the `Summary` component, optimizing the conditional rendering based on the length of `memory.plugins_results`.
=> Front fixes - Logs error and server components

app/lib/pages/speaker_id/page.dart, app/lib/providers/capture_provider.dart, app/lib/providers/speech_profile_provider.dart
- Refactor: Updated the `SpeechProfileProvider` class to improve loading state management, WebSocket setup, and profile completion handling.
- New Feature: Added a new getter `bleBytesStream` in `CaptureProvider` for better data encapsulation.
- Refactor: Split the `resetState` function in `CaptureProvider` into `resetForSpeechProfile` and `resetState` for improved modularity.
- New Feature: Introduced a `restartAudioStreaming` parameter in `resetState` to provide more control over audio streaming behavior.
=> Change speech profile audio bytes and ws setup

app/lib/pages/capture/page.dart, app/lib/pages/onboarding/find_device/found_devices.dart, app/lib/pages/onboarding/speech_profile_widget.dart, app/lib/pages/speaker_id/page.dart, app/lib/providers/capture_provider.dart, app/lib/providers/device_provider.dart, app/lib/providers/speech_profile_provider.dart, app/lib/providers/websocket_provider.dart
- New Feature: Introduced a mechanism to close WebSocket connections with specific reasons, improving the management of WebSocket connections.
- Refactor: Updated navigation flow upon DEVICE_CONNECTED event for better user experience.
- New Feature: Enhanced UI interactions in `SpeakerIdPage` and `SpeechProfileWidget`, including progress indicators during initialization and prompts for firmware updates.
- Refactor: Improved reset state functionality in `CaptureProvider` and introduced asynchronous operations for better performance.
- New Feature: Added new status flags and functions in `SpeechProfileProvider` to manage device initialization and finalization processes more effectively.
=> Websocket fixes and improvements

app/lib/pages/onboarding/wrapper.dart
#748 
```
- Refactor: Updated the onboarding process in the application. Instead of navigating to the next page in the onboarding sequence, users will now be directly routed to the Home Page after completing the onboarding steps. This change enhances the user experience by providing a smoother transition from onboarding to actual usage of the app.
```
=> Fix check it out for 1.0.2 devices

app/lib/pages/onboarding/speech_profile_widget.dart, app/lib/providers/speech_profile_provider.dart
---
- Refactor: Updated the handling of WebSocket closure in the speech profile feature. This change ensures a more reliable and efficient shutdown process when exiting the speech profile setup, enhancing the stability of the application.
---
=> Make close func call in onboarding speech profile synchronous

app/android/app/build.gradle
---
- Chore: Updated the Android app's dependencies by adding OkHttp library. This change will enhance network operations in the app, leading to improved performance and reliability in data transmission.
---
=> pin latest okhttp version

app/lib/main.dart, app/lib/pages/onboarding/speech_profile_widget.dart, app/pubspec.yaml
---
- New Feature: Implemented Bluetooth permission handling in the app initialization process. This ensures that the necessary permissions are granted before any Bluetooth operations are performed, enhancing the app's reliability and user experience.
- Refactor: Updated the logic in the onboarding speech profile widget to improve its functionality. This change enhances the overall performance of the onboarding process, providing a smoother user experience.
---
=> Fix BLE on Android and Speech Profile skip during onboarding

app/pubspec.yaml, backend/database/memories.py, backend/routers/transcribe.py
```
- Refactor: Optimized the `store_model_emotion_predictions_result` function in `backend/database/memories.py` for better performance. The counter now resets every 100 iterations instead of 400, improving memory management.
- Chore: Removed unnecessary print statements from `stream_transcript`, `_create_memory`, and `websocket_endpoint` functions in `backend/routers/transcribe.py` to clean up console output and enhance readability.
```
=> Zrjbthms remove log minor fix

app/lib/backend/schema/memory.dart, app/lib/pages/capture/widgets/widgets.dart, app/lib/pages/home/page.dart, app/lib/pages/memories/widgets/capture.dart, app/lib/pages/memories/widgets/processing_capture.dart, app/lib/widgets/transcript.dart
- Refactor: Updated `ServerProcessingMemory` class for consistent handling of time zones in timestamps.
- Refactor: Simplified the UI for recording, enhancing readability and user experience. This includes renaming `CaptureWidget` to `LiteCaptureWidget`, improving text handling, and removing unnecessary UI elements.
- Style: Optimized the UI layout in `_HomePageState` by replacing an unnecessary `Expanded` widget with a `SizedBox`.
=> Simplify UI for recording

app/lib/pages/memories/widgets/processing_capture.dart, app/lib/widgets/transcript.dart, backend/routers/transcribe.py
- Bug Fix: Improved text display in the transcript widget by trimming unnecessary whitespace and newlines.
- Refactor: Enhanced navigation experience in the memories page by adding a conditional check before navigating to another page.
- Bug Fix: Strengthened error handling in the backend transcribe router, providing more specific WebSocket closure codes for better debugging and stability.
=> Fix text with \n\n on 1 line text view

app/lib/pages/chat/page.dart, app/lib/pages/home/page.dart, app/lib/pages/memories/page.dart, app/lib/providers/home_provider.dart
This PR addresses the issue of the Memories and Chat pages being rebuilt with every interaction, reducing memory usage and improving app performance. It also optimizes the use of providers by relocating them to the specific widgets where they are required, thereby minimizing unnecessary widget rebuilds when changes occur.
```
- Refactor: Optimized the ChatPage, HomePage, and MemoriesPage widgets to enhance app performance and user experience. This includes reducing unnecessary rebuilds and improving memory usage.
- New Feature: Updated UI responsiveness based on focus changes in memory and chat fields, providing a smoother interaction for users.
- Chore: Improved resource management by implementing cleanup logic in the `dispose` method of the home provider.
```
=> Avoid unnecessary widget rebuilds

app/lib/backend/auth.dart, app/lib/main.dart, app/lib/pages/onboarding/wrapper.dart, app/lib/pages/settings/page.dart, app/lib/providers/auth_provider.dart
This PR improves auth provider and fixes few issues related to auth (like idTokenChanges printing multiple times etc) and makes it more reactive to user state change
- Refactor: Enhanced the `AuthenticationProvider` class to improve the authentication process, making it more reactive to user state changes.
- Bug Fix: Fixed issues related to authentication and improved its reactivity by restructuring the initialization process.
- New Feature: Introduced a `DeciderWidget` for better state management and smoother navigation experience upon signing out.
- Chore: Removed redundant function calls in the onboarding process for cleaner code and improved performance.
=> Make auth more reactive

app/lib/backend/auth.dart, app/lib/main.dart, app/lib/pages/home/page.dart, app/lib/utils/logger.dart, app/pubspec.yaml
Related to #658 
- New Feature: Introduced a custom `Logger` class for enhanced logging and global error handling, improving the stability of the application.
- Refactor: Updated sign-in functions (`signInWithApple` and `signInWithGoogle`) to utilize the new `Logger` class for better error management.
- New Feature: Added a `CustomErrorWidget` in `main.dart` for displaying errors in a user-friendly manner.
- Refactor: Modified UI rendering logic on the home page, enhancing the dropdown selection feature's layout and behavior. This change improves user interaction with plugin selection and messaging functionality.
=> Logging and Global Error Handling

app/lib/backend/http/api/memories.dart, app/lib/backend/schema/geolocation.dart, app/lib/backend/schema/structured.dart, app/lib/utils/audio/foreground.dart
Issue: https://github.com/BasedHardware/omi/issues/782
---
- Bug Fix: Updated the handling of various datetime fields across the application to ensure they are converted to UTC before being sent to the backend or serialized. This change ensures consistent time data across different time zones, improving the accuracy and reliability of features that rely on these timestamps.
---
=> Convert toUtc before send it to backend

app/lib/backend/http/api/messages.dart, app/lib/backend/http/api/plugins.dart, app/lib/backend/http/cloud_storage.dart, app/lib/backend/http/openai.dart, app/lib/backend/http/webhooks.dart, app/lib/main.dart, app/lib/pages/home/firmware_update.dart, app/lib/pages/home/page.dart, app/lib/pages/memory_detail/page.dart, app/lib/pages/memory_detail/widgets.dart, app/lib/pages/onboarding/wrapper.dart, app/lib/pages/plugins/plugin_detail.dart, app/lib/pages/settings/recordings_storage_permission.dart, app/lib/pages/settings/webview.dart, app/lib/providers/auth_provider.dart, app/lib/providers/device_provider.dart, app/lib/utils/audio/wav_bytes.dart, app/lib/utils/ble/connected.dart, app/lib/utils/ble/friend_communication.dart, app/lib/utils/ble/gatt_utils.dart, app/lib/utils/features/calendar.dart
- Bug Fix: Improved error handling and robustness in HTTP API calls and Bluetooth operations, reducing the likelihood of crashes due to unexpected responses or connection issues.
- Refactor: Enhanced sign-in process with better error messaging and conditional sign-in attempts, improving user experience during authentication.
- Bug Fix: Ensured UI updates only occur when components are mounted, preventing potential crashes during asynchronous operations.
- Refactor: Optimized event handling in CalendarUtil by adjusting time zone usage, enhancing accuracy of event timings.
- Bug Fix: Added checks for file existence before deletion, preventing errors related to non-existent files.
=> Fix issues caught by Instabug

app/lib/pages/chat/page.dart, app/lib/providers/message_provider.dart
closes #788 
- New Feature: Enhanced the chat functionality in the `ChatPageState` and `MessageProvider` classes. Now, messages sent to the server include a `pluginId` parameter. This update allows for better identification and handling of messages associated with specific plugins, improving the overall user experience in plugin-based interactions within the chat feature.
=> Fix plugin in chat not working

backend/utils/audio.py
- New Feature: Enhanced audio processing capabilities in our backend utilities. We've added support for the `pcm8` codec, allowing users to create WAV files from bytes using this format. This update provides more flexibility and options in handling and generating audio data.
=> Support pcm8 on new memory watch transcript

app/lib/backend/schema/message.dart, app/lib/main.dart, app/lib/pages/home/page.dart, app/lib/providers/capture_provider.dart, app/lib/providers/device_provider.dart, app/lib/providers/memory_provider.dart, app/lib/utils/audio/wav_bytes.dart, app/lib/utils/ble/communication.dart, app/lib/utils/ble/connected.dart, app/lib/utils/ble/friend_communication.dart, app/lib/utils/ble/gatt_utils.dart
Related to #516 
- Bug Fix: Improved error handling for Bluetooth device disconnection scenarios, ensuring smoother user experience.
- Refactor: Enhanced image loading efficiency in the home page by utilizing `CachedNetworkImage`, improving app performance and user experience.
- Bug Fix: Added robust error handling for audio decoding and RSSI reading processes, increasing app stability.
- Chore: Removed unnecessary internet connection check at app startup and redundant memory retry calls, optimizing app performance.
- New Feature: Introduced logging for better tracking of device connection issues, aiding in future debugging and issue resolution.
=> Instabug Fixes

app/lib/pages/memories/page.dart
I'm sorry, but I can't generate release notes as you requested because the variable `$raw_summary` you provided doesn't contain any actual data. Please provide the summary of changes made in the code so that I can help you craft concise and meaningful release notes.
=> Add pull to refresh for memories screen

backend/models/processing_memory.py, backend/routers/processing_memories.py
Reverts BasedHardware/omi#811
not work as expected, the response time looks higher ???
=> Revert "Trim the unnecessary data for updating processing memory api"

app/lib/main.dart, app/lib/pages/home/page.dart, app/lib/providers/capture_provider.dart, app/lib/services/services.dart
---
- New Feature: Implemented background services and app lifecycle event handling for improved user experience during multitasking.
- Refactor: Introduced watchdog for UI state monitoring, enhancing app stability and performance.
- Refactor: Updated `ServiceManager` and `MicRecorderService` classes to accommodate new background service functionality.
- Bug Fix: Adjusted recording state update in `streamRecordingOnAndroid()` method for more accurate state tracking.
- New Feature: Added debug prints for better real-time app monitoring and troubleshooting.
---
=> Add watchdog to monitor ui sate

app/lib/pages/memories/widgets/processing_capture.dart, app/lib/providers/capture_provider.dart, app/lib/services/services.dart, app/pubspec.yaml
- Refactor: Centralized the microphone recording logic in the `CaptureProvider` class, improving code maintainability and consistency across platforms.
- New Feature: Added a parameter `isInBG` to the `MicRecorderService` constructor, enabling better handling of background recording scenarios on Android devices. This enhances user experience by ensuring seamless audio recording even when the app is running in the background.
=> Centralize mic recorder logic

app/lib/services/services.dart
- Refactor: Enhanced the `ServiceManager` and `MicRecorderBackgroundService` for better performance and maintainability. The `backgroundRunner` property has been removed from `ServiceManager`, simplifying its structure.
- New Feature: Introduced an `ensureRunning` method to `BackgroundService` which ensures that the service is running when required, improving reliability.
- Refactor: The initialization of `MicRecorderBackgroundService` now directly uses a new instance of `BackgroundService`, streamlining the process and reducing complexity.
=> Updates: Ensure running for background recording every session

backend/database/trends.py, backend/main.py, backend/models/trend.py, backend/routers/trends.py, backend/utils/llm.py, backend/utils/memories/process_memory.py
- implementation of models to map trend-related objects
- trigger new thread to execute trend-extraction methods for all memories
- implementation of new prompt to extract trends from transcript
- store identified trends in db according to values defined on TrendEnum
- implementation of trend-related data extraction from db
- implementation of GET endpoint ("/v1/trends") to get trend-related data from db
https://github.com/user-attachments/assets/b207c90f-c98d-48a2-bcbe-68dc2a66ff96
=> feature: trend management (backend)

app/lib/pages/memories/page.dart, app/lib/pages/memories/widgets/capture.dart, app/lib/pages/memories/widgets/processing_capture.dart
- New Feature: Enhanced the location permissions request process for a smoother user experience.
- Refactor: Moved location permission dialog functionality from `capture.dart` to `page.dart` for better code organization and maintainability.
- Bug Fix: Fixed an issue in `processing_capture.dart` where a premature dialog closure was occurring during the recording initialization process. This fix ensures the dialog closes at the appropriate time, improving the user experience.
=> Move location permission and minor ux improvement for mic dialog

app/lib/pages/memories/widgets/capture.dart, app/lib/providers/capture_provider.dart, backend/database/processing_memories.py, backend/models/processing_memory.py, backend/routers/processing_memories.py, backend/routers/transcribe.py, backend/utils/audio.py, backend/utils/other/storage.py, backend/utils/processing_memories.py
- New Feature: Added an optional `audio_url` field to the `ProcessingMemory` class for storing audio data.
- New Feature: Introduced functions to retrieve the last processing memory for a user and update memory segments, enhancing user interaction with past memories.
- New Feature: Implemented `merge_wav_files` function to combine multiple WAV files into one, improving audio handling.
- New Feature: Added `download_postprocessing_audio` function to facilitate downloading of audio files from Google Cloud Storage.
- Refactor: Updated the `update_processing_memory` function to `update_basic_processing_memory` for better clarity and maintainability.
- Refactor: Removed unused `processCachedTranscript` method from the `CaptureProvider` class, simplifying the codebase.
=> Combine processing memories

backend/routers/transcribe.py
- New Feature: Updated the transcription functionality to include a duration limit. This ensures that data transmission stops when the total time exceeds the specified duration, enhancing efficiency and control over resource usage.
- Refactor: Adjusted the calculation of transcription duration based on the length of the speech profile for improved accuracy.
- Bug Fix: Modified the duration calculation logic to prevent potential overestimation of transcription time.
=> Send initial file with duration limit

app/ios/Podfile, app/lib/main.dart, app/lib/pages/memory_detail/widgets.dart, app/lib/pages/settings/calendar.dart, app/lib/providers/calendar_provider.dart, app/lib/utils/features/calendar.dart, app/pubspec.yaml
- New Feature: Enhanced calendar access and event handling. Users will now experience improved permission checks and UI feedback for calendar access.
- Refactor: Updated the `CalendarPage` class to extend `StatefulWidget` for better state management.
- New Feature: Introduced a new package (`manage_calendar_events`) for managing calendar events, providing a more robust and efficient way of handling calendar operations.
- Refactor: Replaced the previous implementation of displaying events with a new `EventsListWidget` class in the memory detail page, improving modularity and readability.
- Bug Fix: Adjusted event start and end times to consider local timezone and UTC offset, ensuring accurate event timing across different time zones.
=> Fix calendar issues

plugins/example/basic/memory_created.py
makes the response feel more human and natural
=> edited the prompt of the feedback to be less generic

app/lib/main.dart, app/lib/utils/logger.dart
- New Feature: Introduced `LoggerSnackbar` widget for enhanced error and exception handling. This feature provides a user-friendly way to display errors and exceptions.
- Refactor: Updated the `_MyAppState` class to use the new `LoggerSnackbar` widget in `exceptionAlertBuilder` and `errorAlertBuilder`, improving the visibility and clarity of error messages.
- New Feature: Added an action button within the `LoggerSnackbar` widget that allows users to share errors for further investigation, enhancing the app's debugging capabilities.
=> Improve logger snackbar and open gleap

frontend/src/app/dreamforce/page.tsx, frontend/src/components/trends/get-trends-main-page.tsx
- New Feature: Expanded the trends categories on the main page to include 'industry', 'innovation', 'research', 'product', and 'event' for a more comprehensive user experience.
- Refactor: Improved code readability and consistency by introducing a utility function `capitalizeFirstLetter` to handle string capitalization dynamically.
- Style: Enhanced the UI layout and styling of the trends main page for better user interaction.
- New Feature: Updated the Dreamforce page with a new loading state that includes a spinning circle icon and a message, improving user experience during data fetch operations.
=> Frontend Trends: Improving UI and functionality 

frontend/src/components/trends/get-trends-main-page.tsx
- Refactor: Enhanced the Trends display component on the main page. The update improves the visual presentation and layout of trending topics, making it easier for users to distinguish between the best and worst performing trends within each category. This change aims to provide a more intuitive and engaging user experience when exploring trends.
=> Frontend Trends: UI improvements

frontend/src/components/trends/get-trends-main-page.tsx
```
- Bug Fix: Corrected spelling errors in the Trends Main Page component. The term "Conversartion" has been corrected to "Conversation". This change improves the readability and understanding of the interface for users.
```
=> Frontend Trends: Fix "conversartion" spelling error

app/lib/main.dart, app/lib/pages/capture/widgets/widgets.dart, app/lib/pages/home/page.dart, app/lib/pages/memory_detail/page.dart, app/lib/pages/memory_detail/widgets.dart, app/lib/pages/onboarding/memory_created_widget.dart, app/lib/pages/onboarding/wrapper.dart, app/lib/widgets/photos_grid.dart
---
- New Feature: Added functionality for setting up speaker profiles, enhancing the onboarding experience.
- Refactor: Optimized memory detail page rebuilding and event display for improved performance.
- Bug Fix: Fixed exceptions in onboarding process and improved navigation.
- New Feature: Implemented event time filtering in `EventsListWidget` for better event management.
- Refactor: Adjusted geolocation widgets layout for better UI consistency.
- New Feature: Added a function to convert minutes to hours or days, improving event duration representation.
---
=> Fixes and Improvements

app/lib/providers/capture_provider.dart, app/lib/providers/memory_provider.dart
---
- New Feature: Added automatic event creation for memories based on user-defined conditions and settings. This feature will help users to keep track of their important memories without manual intervention.
- Bug Fix: Implemented a check to prevent duplicate event creation. This fix ensures that each memory is associated with a unique event, avoiding any confusion or clutter in the user's calendar.
---
=> Create calendar events automatically

app/lib/pages/onboarding/permissions/permissions_widget.dart
- Refactor: Enhanced the efficiency of the permissions handling logic in the onboarding process. This update ensures a smoother user experience during the app setup.
- New Feature: Introduced additional checks and delays for location permission requests, providing users with more control and understanding over their privacy settings.
- Bug Fix: Improved the handling of notification and location permissions to prevent potential issues and enhance overall app performance.
=> Improve permission handling on onboarding

app/lib/providers/message_provider.dart, backend/database/chat.py, backend/routers/chat.py, backend/utils/chat/chat.py
- New Feature: Introduced a function `clear_user_chat_message` to efficiently clear user chat messages.
- Bug Fix: Improved error handling in the `clear_chat` function, now returns an error message instead of raising exceptions.
- Refactor: Optimized `batch_delete_messages` function with pagination for better performance during batch deletion of messages.
- Bug Fix: Updated logic in `message_provider.dart` to correctly set `hasCachedMessages` flag when messages are retrieved from the server or loaded from cache.
=> Chat Clear Fixes and Improvements

plugins/example/README.md
fixed fastapi run command in readme
=> Updated Plugin README.md

app/lib/pages/onboarding/wrapper.dart
- New Feature: Enhanced accessibility support on the onboarding screen. The layout, text sizes, and scrolling behavior have been adjusted to better accommodate users with varying text scales. This ensures a more inclusive and user-friendly experience for all users, regardless of their text size preferences.
=> Handle large text size (accessibility) on onboarding

app/lib/pages/chat/widgets/ai_message.dart, app/lib/pages/memories/page.dart, app/lib/pages/memories/widgets/memory_list_item.dart, app/lib/pages/memory_detail/memory_detail_provider.dart, app/lib/pages/onboarding/memory_created_widget.dart, app/lib/providers/memory_provider.dart
https://github.com/user-attachments/assets/2f07e302-f8f7-4140-a910-831e51ee77da
- New Feature: Memories are now grouped by date for a more organized view.
- Performance: Improved memory management operations, enhancing the app's performance.
- Refactor: Reworked the logic for sorting and filtering memories, making it more efficient and maintainable.
- Update: Adjusted widget heights for optimized layout and better user experience.
=> Improve memories handling

app/lib/backend/http/api/memories.dart, app/lib/pages/memories/widgets/processing_capture.dart, app/lib/providers/capture_provider.dart, app/lib/providers/memory_provider.dart, backend/routers/processing_memories.py
- Refactor: Enhanced the `getProcessingMemories` function by removing a debug print statement and increasing the limit parameter from 3 to 5, allowing users to view more processing memories at once.
- Style: Improved the UI of the `getProcessingMemoriesWidget` method by adding dynamic padding based on the index value, providing a better visual experience for users.
- New Feature: Updated the `CaptureProvider` and `MemoryProvider` classes to handle new capturing memory status. This feature will notify users about the status of their capturing memories and update the processing memories accordingly.
=> Tracking the memory >;2ucapturing status

app/lib/pages/memories/widgets/processing_capture.dart, app/lib/providers/capture_provider.dart, app/lib/providers/speech_profile_provider.dart, app/lib/services/sockets/transcription_connection.dart, backend/models/processing_memory.py, backend/routers/transcribe.py
- New Feature: Enhanced real-time transcription service with improved socket connection handling. Users will now be notified upon successful connection establishment.
- Refactor: Streamlined the process of creating and updating processing memories in the backend, ensuring consistent setting of capturing time and better handling of existing memories.
- New Feature: Introduced a method to predict future capturing times based on current conditions, improving the accuracy of memory processing.
- Refactor: Redesigned the memory capture widget in the app for better user experience. The layout now adapts more intuitively to different states such as reconnecting, processing, listening, and preparing.
=> Inwdx processing memory ux clean 868

app/lib/pages/chat/widgets/ai_message.dart, app/lib/pages/home/page.dart, app/lib/pages/memory_detail/widgets.dart, app/lib/pages/onboarding/permissions/permissions_widget.dart, app/lib/services/notifications.dart
---
- **Enhancement**: Improved text decoding and handling of special characters in chat messages for better user experience.
- **New Feature**: Added functionality to register for notifications based on user preferences during the initialization of the home page.
- **Refactor**: Changed `_register` method to `public` in `NotificationService` class, enhancing its accessibility.
- **UI Improvement**: Updated titles and descriptions in PermissionsWidget for better clarity and user understanding.
=> Notifications, Chat and other Improvements and Fixes

app/lib/pages/memories/widgets/memory_list_item.dart, app/lib/pages/memories/widgets/processing_capture.dart, app/lib/providers/memory_provider.dart
- New Feature: Introduced a timer to automatically reset the 'new' status of a memory item after 60 seconds, enhancing user experience.
- New Feature: Added a `MemoryNewStatusIndicator` widget that blinks to indicate a new memory, providing a more intuitive interface for users.
- Refactor: Improved the display logic for the new status in the UI and decoration logic for the memory item widget, leading to cleaner code and potentially smoother UI transitions.
- Refactor: Streamlined the handling of SD card functionality and memory headers in `_MemoryCaptureWidgetState`, improving code maintainability.
- Bug Fix: Added null check for the `_getMemoryHeader` function return value, preventing potential crashes.
- Refactor: Updated the `MemoryProvider` class to better handle processing and …
=> Fdhzb codebase clean up 866

app/lib/pages/chat/widgets/ai_message.dart, app/lib/pages/chat/widgets/typing_indicator.dart
---
- Style: Improved the visual layout of chat widgets in the application. This includes better spacing and sizing adjustments for a more streamlined user experience.
- Refactor: Adjusted the size of the typing indicator bubble for better visibility and consistency within the chat interface.
---
=> Minor chat improvements

app/lib/pages/memories/widgets/processing_capture.dart
- New Feature: Introduced a readiness state for the memory processing page. This improves user experience by providing visual feedback during initialization.
- Refactor: Enhanced the handling of device and transcript service statuses, leading to more accurate UI updates based on these states.
- Chore: Improved resource management with proper initialization and disposal of timers used in the application.
=> Enhance ws drop state on the capturing widget

app/lib/backend/http/api/memories.dart, app/lib/backend/preferences.dart, app/lib/services/wals.dart
- New Feature: Introduced `syncLocalFiles` function to synchronize local files with the backend server, enhancing data consistency and reliability.
- Refactor: Updated key used in SharedPreferences from `wals` to `v2/wals`, improving data storage and retrieval process.
- Refactor: Renamed and updated functions in `WalService` for better clarity and functionality.
- New Feature: Added `onClosed` method to handle specific scenarios when the application is closed, improving user experience and data integrity.
=> Jzecm wal local sync 958

app/lib/pages/home/page.dart, app/lib/pages/memory_capturing/page.dart
https://github.com/user-attachments/assets/ce2d71b2-971e-42a5-a1be-c6480e912de5
- New Feature: Introduced a timer functionality to the `MemoryCapturingPage`. Users can now track the elapsed time during memory capturing sessions, enhancing their ability to manage and monitor their activities. The elapsed time is displayed in an easy-to-read HH:MM:SS format.
=> Minor UI Improvements

backend/routers/sdcard.py
Pull: https://github.com/BasedHardware/omi/pull/994
=> Remove redundant log from sdcard router

app/lib/env/env.dart, app/lib/providers/device_provider.dart, app/lib/services/devices.dart, backend/routers/transcribe_v2.py, backend/utils/stt/streaming.py
=> Handle 429 error on Deepgram connection

backend/Dockerfile, backend/requirements.txt
Reverts BasedHardware/omi#1170
=> Revert "Graphviz docker fix"

backend/routers/transcribe_v2.py
Reverts BasedHardware/omi#1176
=> Revert "Add simple tracing stream_transcript"

backend/utils/pusher.py, backend/utils/webhooks.py
Reverts BasedHardware/omi#1204
=> Revert "On message for keep-alived pusher socket"

backend/utils/webhooks.py
=> Add notification to the webhook realtime transcript

docs/docs/developer/apps/Submitting.mdx
Change community-apps.json to community-plugins.json
=> Minor docs edit

README.md, app/lib/pages/settings/about.dart
=> Update discord links

backend/routers/apps.py, backend/routers/plugins.py
Reverts BasedHardware/omi#1284
=> Revert "Disable proactive notifications temporarily"

backend/routers/pusher.py, backend/routers/transcribe_v2.py, backend/utils/pusher.py, backend/utils/webhooks.py
Backend should reconnect to Pusher if there any wrong with the connection.
=> Add pusher reconnect

backend/routers/apps.py
=> chore: add notification & rename title app capablilities

frontend/src/app/apps/[id]/page.tsx, frontend/src/app/apps/page.tsx
=> Use approved-apps endpoint for webapp and minor ui fixes

backend/routers/apps.py, backend/routers/plugins.py
=> Apps endpoint minor improvements

app/lib/pages/apps/update_app.dart
=> add Notification Scopes to updating an app

app/lib/pages/apps/list_item.dart, app/lib/providers/app_provider.dart
=> Fix index issues on visibility change and delete

backend/database/apps.py, backend/database/redis_db.py, backend/routers/plugins.py, backend/utils/apps.py
=> Count usage and money from 1st nov and fix for new apps

app/lib/pages/home/page.dart, app/lib/services/notifications.dart
=> redirect to the chat when click on a notification

backend/database/mem_db.py, backend/database/redis_db.py, backend/utils/plugins.py
=> Rate limits 01 proactive noti per user per 30 seconds

app/lib/services/notifications.dart
=> Dont show the local notification on message recevied on iOS

frontend/next.config.mjs, frontend/public/.well-known/apple-app-site-association, frontend/public/.well-known/assetlinks.json
=> Add Google and Apple deeplink verification assets

app/android/app/proguard-rules.pro, app/android/app/src/main/AndroidManifest.xml, app/ios/Runner/Info.plist, app/ios/Runner/Runner.entitlements, app/ios/Runner/RunnerDebug-dev.entitlements, app/ios/Runner/RunnerDebug-prod.entitlements, app/ios/Runner/RunnerProfile-dev.entitlements, app/ios/Runner/RunnerProfile-prod.entitlements, app/ios/Runner/RunnerRelease-dev.entitlements, app/ios/Runner/RunnerRelease-prod.entitlements, app/lib/main.dart, app/lib/pages/apps/app_detail/app_detail.dart, app/lib/providers/app_provider.dart, app/pubspec.yaml
closes #1345 
https://github.com/user-attachments/assets/0e684be6-5270-441e-ae0c-c55c163b234b
=> Add support for deeplinks in Apps

backend/utils/llm.py
=> Support follow up question in chat

backend/database/redis_db.py, backend/utils/apps.py
=> chore: using mget when get plugin for /apps

app/lib/pages/apps/app_detail/app_detail.dart, docs/docs/developer/apps/Submitting.mdx
https://discord.com/channels/1192313062041067520/1226079093859287051/1309627900680474714
https://discord.com/channels/1192313062041067520/1226079093859287051/1309261568009306153
=> Fix rounding bug + Edit docs

app/lib/pages/apps/explore_install_page.dart, app/lib/pages/apps/widgets/app_section_card.dart
=> UI fixes for small screen devices

app/lib/pages/apps/page.dart, app/lib/pages/memory_detail/widgets.dart
=> Show app bar in apps page when navigating from memory detail page

backend/routers/apps.py
Set default deleted value while submitting the app to avoid inconsistencies
=> Set default deleted value to avoid inconsistencies

backend/routers/notifications.py
So that the admins can send communication notifications (like the payouts) anytime
=> Add notification endpoint for admins

app/lib/pages/home/firmware_mixin.dart, app/lib/pages/home/firmware_update.dart, backend/routers/firmware.py
=> Add support OTA firmware updates DK2

frontend/src/app/apps/layout.tsx, frontend/src/app/page.tsx, frontend/src/components/shared/app-header.tsx
; modify app header visibility
- Changed the redirection from '/memories' to '/apps' in the Home component.
- Removed the static header from the DashboardLayout component.
- Updated the AppHeader component to conditionally display a hackathon announcement based on the current pathname, ensuring it does not show on the '/apps' page.
=> Update redirection and layout for apps page

frontend/src/app/apps/[id]/page.tsx, frontend/src/app/apps/category/[category]/page.tsx, frontend/src/app/apps/components/app-list.tsx, frontend/src/app/apps/components/category-nav/index.tsx, frontend/src/app/apps/components/plugin-card/compact.tsx, frontend/src/app/apps/components/plugin-card/featured.tsx, frontend/src/app/apps/hooks/useClickOutside.ts, frontend/src/app/apps/page.tsx, frontend/src/app/apps/popular/page.tsx, frontend/src/app/apps/utils/category.ts, frontend/src/components/shared/app-header.tsx
- Replaced the existing plugin listing with a new AppList component in the main Apps page. ent with dropdown functionality for better category selection and added icons for categories.
- Improved the PluginDetailView layout and related apps section, utilizing a new CompactPluginCard for a cleaner presentation.
- Refactored the AppHeader component to support dynamic navigation items and improved mobile menu functionality.
=> Refactor Apps Page and Enhance Category Navigation

frontend/src/app/apps/components/app-list.tsx, frontend/src/app/apps/components/category-header/index.tsx, frontend/src/app/components/product-banner/index.tsx, frontend/src/app/globals.css, frontend/src/components/shared/footer.tsx
- Added a new gradient animation for background effects in the ProductBanner and other components.
- Updated spacing in AppList and CategoryHeader for improved layout consistency.
- Refactored ProductBanner to enhance visual appeal and responsiveness with new gradient backgrounds and hover effects.
- Added 'rel="noreferrer"' to external links in the footer for security improvements.
=> Enhance UI with gradient animations and layout adjustments

frontend/src/app/apps/[id]/page.tsx, frontend/src/components/shared/gleap.tsx, frontend/src/components/shared/google-analytics.tsx
- Updated the canonical URL in the structured data generation to use the dynamic WEB_URL from envConfig for better maintainability.
- Temporarily disabled the Gleap initialization in the GleapInit component to prevent errors when the API key is not set.
These changes enhance the application's configuration management and prevent potential issues with Gleap integration.
=> Refactor URL handling and temporarily disable Gleap initialization

backend/utils/llm.py
Closes #1476
This should give GPT more clarity on what type of values exactly the each field expects
=> Add example values for ExtractedInformation

app/lib/pages/conversations/widgets/empty_conversations.dart, app/lib/pages/home/page.dart, backend/database/redis_db.py, backend/main.py, backend/models/app.py, backend/requirements.txt, backend/routers/apps.py, backend/routers/payment.py, backend/utils/apps.py, backend/utils/stripe.py
=> Onvme apps payment 1404

frontend/src/components/shared/app-header.tsx
- Moved mobile menu panel outside of the header for better structure and accessibility.
- Fixed Menu Background
=> Refactor mobile menu implementation in AppHeader component

Friend/firmware/firmware_v1.0/src/sdcard.c, Friend/firmware/firmware_v1.0/src/sdcard.h, Friend/firmware/firmware_v1.0/src/transport.c
Add a mutex to make sure writing sd card is done before enter low power mode.
=> #1512: Make sure sd card is totally off before enter low power mode.

frontend/src/lib/api/apps.ts
Cache successful responses in memory
Return cached data when hitting rate limits
Maintain the existing React cache functionality
Provide better error handling
=> Preventing Rate Limiting errors.

frontend/src/app/apps/category/[category]/page.tsx, frontend/src/app/apps/utils/metadata.ts, frontend/src/app/components/product-banner/index.tsx
- Introduced a new utility function `getCategoryMetadata` to streamline metadata retrieval for categories.
- Removed outdated metadata checks in `generateMetadata` function, improving clarity and efficiency.
- Updated styles in the `ProductBanner` component for improved responsiveness and visual appeal, including hover effects and spacing adjustments.
=> Refactor category metadata handling and enhance product banner styles

app/lib/providers/device_provider.dart, app/lib/services/notifications.dart
I wanted the notifications to look the same. You can see how they were different in the screenshot.
=> Change notifications for consistency

backend/utils/apps.py
=> Add marketplace app review uids

backend/routers/apps.py, backend/utils/apps.py
=> Add get app plans by permit checks

app/lib/backend/http/api/apps.dart, app/lib/pages/apps/add_app.dart, app/lib/pages/apps/providers/add_app_provider.dart, app/lib/pages/apps/update_app.dart, app/lib/pages/apps/widgets/app_metadata_widget.dart
=> Do not show paid plans option if plans empty

app/lib/pages/apps/add_app.dart, app/lib/pages/apps/app_detail/app_detail.dart, app/lib/pages/apps/app_detail/reviews_list_page.dart, app/lib/pages/apps/app_detail/widgets/add_review_widget.dart, app/lib/pages/apps/list_item.dart, app/lib/pages/apps/widgets/app_section_card.dart
Closes #1475 
https://github.com/user-attachments/assets/31920dd2-ef53-44ea-8f5b-1026f1065f00
https://github.com/user-attachments/assets/c4a4437b-3d54-4e03-b345-489260ea9912
=> Fix Small Screen UI Overflow Issues

backend/database/vector_db.py, backend/utils/llm.py, backend/utils/memories/process_memory.py, backend/utils/retrieval/graph.py
=> Qjufa chat 1414

app/lib/pages/onboarding/find_device/found_devices.dart, app/lib/providers/onboarding_provider.dart
=> Show snackbar instead of dialog for openglass support

README.md
=> Fix borked app setup link

app/lib/backend/preferences.dart, app/lib/pages/apps/app_detail/app_detail.dart
=> Show data disclaimer dialog for external apps

app/lib/backend/schema/conversation.dart, app/lib/main.dart, app/lib/pages/conversation_detail/conversation_detail_provider.dart, app/lib/pages/conversation_detail/page.dart, app/lib/pages/settings/profile.dart, app/lib/pages/speech_profile/page.dart, app/lib/widgets/transcript.dart, backend/routers/transcribe_v2.py
Part of #1230 
https://github.com/user-attachments/assets/c1a99a97-1a13-4fe2-86c0-70607fdf3425
https://github.com/user-attachments/assets/9add1b5d-8479-41ea-ad4a-62bb4bd11c87
=> Restore ability to set Speaker to transcripts

app/lib/pages/conversations/widgets/processing_capture.dart, app/lib/pages/home/device.dart, app/lib/pages/home/widgets/battery_info_widget.dart, app/lib/providers/capture_provider.dart, app/lib/providers/device_provider.dart, app/lib/services/devices/friend_connection.dart
=> UX enhancement, on device connection state and battery level as well

backend/routers/apps.py
=> Remove trailing/leading spaces from webhook url

app/lib/backend/http/api/conversations.dart, app/lib/pages/conversation_detail/conversation_detail_provider.dart
=> don't check if conversation recording exists (coz not needed)

app/lib/backend/http/api/conversations.dart, app/lib/backend/schema/conversation.dart, app/lib/pages/conversation_detail/page.dart, app/lib/pages/conversation_detail/widgets/name_speaker_sheet.dart, app/lib/widgets/transcript.dart, backend/routers/memories.py
https://github.com/user-attachments/assets/ed8ac85f-ff6e-44e8-bce0-44664ec03512
=> Assign segments improvements and multiple segments assigning

.gitignore, app/.vscode/launch.json
It runs now from VSCode directly. It can now hot reload, step debug, inspect widgets, etc...
=> Add Flutter launch configuration VSCode

app/lib/pages/home/page.dart
=> Sync icon state fix

app/lib/pages/conversation_detail/widgets/name_speaker_sheet.dart
=> assign single segment fix

app/lib/providers/app_provider.dart
=> Filter apps after enabling/disabling an app

docs/docs/developer/backend/Backend_Setup.mdx
=> Improve backend setup docs

app/lib/backend/http/api/conversations.dart, app/lib/gen/assets.gen.dart, app/lib/providers/conversation_provider.dart, backend/models/memory.py, backend/routers/memories.py, backend/typesense/memories.schema, backend/utils/memories/search.py
issue: #[1648](https://github.com/BasedHardware/omi/issues/1648)
=> Filter discarded conversations via api

app/lib/pages/facts/page.dart, app/lib/providers/facts_provider.dart
issue: #[1655](https://github.com/BasedHardware/omi/issues/1655)
=> Dadtw facts

app/lib/pages/apps/app_detail/app_detail.dart, app/lib/pages/apps/app_detail/widgets/app_analytics_widget.dart, app/lib/utils/analytics/intercom.dart
closes #1671 
https://github.com/user-attachments/assets/acc46a49-e98b-40ae-9fa1-374e2c9cf823
=> Update App Analytics to reflect new payment system

app/lib/backend/schema/conversation.dart, app/lib/pages/conversations/widgets/conversation_list_item.dart, app/lib/pages/conversations/widgets/search_widget.dart
Reverts BasedHardware/omi#1715
=> Revert "Reduce colors contrast, layers on home page. More infomative convos item"

app/lib/pages/chat/page.dart, app/lib/pages/chat/select_text_screen.dart, app/lib/pages/chat/widgets/message_action_menu.dart
Closes #1725 
https://github.com/BasedHardware/omi/pull/1688#issuecomment-2603533484
https://github.com/user-attachments/assets/f9e24e05-59b1-4e07-9f36-2071b887a510
=> Select text option for chat messages

backend/utils/retrieval/graph.py
Missing the `state.get("plugin_selected")` parameter on calling the `answer simple message` function. resulted omi being selected instead of the specific app.
=> Fix chat with apps on answering the simple question

app/lib/gen/assets.gen.dart, app/lib/pages/payments/models/payment_method_config.dart, app/lib/pages/payments/stripe_connect_setup.dart
=> Asset path fix

app/lib/backend/http/api/apps.dart, app/lib/backend/schema/app.dart, app/lib/pages/apps/add_app.dart, app/lib/pages/apps/app_detail/app_detail.dart, app/lib/pages/apps/providers/add_app_provider.dart, app/lib/pages/apps/update_app.dart, app/lib/pages/apps/widgets/full_screen_image_viewer.dart, app/lib/pages/apps/widgets/show_app_options_sheet.dart, backend/models/app.py, backend/routers/apps.py, backend/utils/other/storage.py
=> Msoej apps thumbnail 1709

app/lib/backend/schema/app.dart, app/lib/pages/apps/app_detail/app_detail.dart, app/lib/pages/apps/app_home_web_page.dart, app/lib/pages/apps/providers/add_app_provider.dart, app/lib/pages/apps/widgets/external_trigger_fields_widget.dart, app/pubspec.yaml, backend/models/app.py
=> Znwec apps home page 1709

app/lib/backend/http/api/apps.dart, app/lib/backend/preferences.dart, app/lib/backend/schema/app.dart, app/lib/main.dart, app/lib/pages/chat/clone_chat_page.dart, app/lib/pages/chat/page.dart, app/lib/pages/home/page.dart, app/lib/pages/home/widgets/chat_apps_dropdown_widget.dart, app/lib/pages/persona/persona_profile.dart, app/lib/pages/persona/persona_provider.dart, app/lib/pages/persona/twitter/verify_identity_screen.dart, app/lib/pages/persona/update_persona.dart, app/lib/utils/other/string_utils.dart, backend/database/apps.py, backend/routers/apps.py, backend/routers/chat.py, backend/utils/llm.py, backend/utils/retrieval/graph.py, backend/utils/social.py
=> Xhxag persona fixes

app/lib/backend/http/api/apps.dart, app/lib/pages/onboarding/auth.dart, app/lib/pages/persona/persona_profile.dart, app/lib/pages/persona/twitter/clone_success_sceen.dart, app/lib/pages/persona/twitter/social_profile.dart, app/lib/pages/persona/twitter/verify_identity_screen.dart, app/lib/widgets/sign_in_button.dart, backend/database/apps.py, backend/routers/apps.py, backend/utils/llm.py, backend/utils/social.py
https://github.com/user-attachments/assets/55509258-1e37-4e2d-8da4-45d13a96382d
=> update clone from device bottom sheet and button

backend/models/app.py, backend/utils/llm.py
=> Use openrouter with gemini and claude sonnet for persona chats

personas-open-source/src/app/(auth)/login/page.tsx, personas-open-source/src/app/chat/page.tsx, personas-open-source/src/app/page.tsx, personas-open-source/src/components/shared/Footer.tsx
=> Fix - Change the year to 2025 from 2024

app/lib/backend/schema/app.dart, app/lib/pages/apps/app_detail/app_detail.dart, app/lib/pages/apps/app_detail/widgets/info_card_widget.dart, app/lib/pages/persona/add_persona.dart, app/lib/pages/persona/persona_provider.dart, app/lib/pages/persona/update_persona.dart, backend/routers/apps.py, backend/utils/apps.py
https://github.com/user-attachments/assets/cbb354ad-1d82-44b6-9d1e-4437c6ab3550
=> make persona connections more clear and improve ux

app/lib/pages/home/page.dart, app/lib/providers/connectivity_provider.dart
=> fix: sign "no internet connection (looks & functionality)

app/lib/backend/http/api/messages.dart, app/lib/backend/preferences.dart, app/lib/backend/schema/message_event.dart, app/lib/pages/conversations/widgets/processing_capture.dart, app/lib/pages/settings/developer.dart, app/lib/providers/capture_provider.dart, app/lib/providers/developer_mode_provider.dart, app/lib/services/sockets.dart, app/lib/services/sockets/pure_socket.dart, app/lib/services/sockets/transcription_connection.dart, backend/models/message_event.py, backend/routers/transcribe_v2.py, backend/utils/memories/location.py, backend/utils/memories/process_memory.py
=> Ciqro Stabilize Transcription Service

backend/routers/transcribe_v2.py
=> Ping fast on /listen API

app/lib/pages/apps/add_app.dart
https://github.com/user-attachments/assets/49379a9e-7af9-459b-bf34-f713256f9913
=> Add payments popup if not connected

app/lib/pages/apps/explore_install_page.dart
Before:
https://github.com/user-attachments/assets/f2a0e001-31f2-4790-a72b-b76111ecc4dc
After:
https://github.com/user-attachments/assets/3862ca85-5bc6-4b0d-8956-a838bf5d3190
=> Add debouncer to reduce search rebuilds

backend/charts/deepgram-self-hosted/dev_omi_values.yaml, backend/charts/deepgram-self-hosted/how_to_deploy_deepgram_self_hosted_on_gke.md, backend/charts/deepgram-self-hosted/prod_omi_values.yaml
**Changes:**
- Upgrade Engine node from **g2-standard-8** to **g2-standard-12** to prevent OOM issue (since we use multilingual models, engine pod will consume more memory)
- Enhance scale up behavior to reduce flappy for autoscaling of Engine pods.
=> Enhance DG self-hosted config

app/lib/pages/apps/widgets/action_fields_widget.dart, backend/models/app.py, backend/models/facts.py, backend/models/integrations.py, backend/models/memory.py, backend/routers/apps.py, backend/routers/integration.py, backend/utils/apps.py, backend/utils/llm.py, backend/utils/llms/fact.py, backend/utils/memories/facts.py, backend/utils/memories/process_memory.py, docs/docs/developer/apps/IntegrationActions.mdx
=> Add the create facts action on external integration

backend/README.md, docs/docs/developer/Compile_firmware.mdx, docs/docs/developer/backend/Backend_Setup.mdx
I will do aggregation to this PR all the minor doc fixes. Feel free to merge it. 
Added Reference to Documentation:
Added a clear reference to the comprehensive Backend Setup documentation at the beginning
Added an "Additional Resources" section at the end with links to full documentation
Improved Structure and Formatting:
Organized the content with clear headings and better formatting
Used consistent bullet points and code blocks for better readability
Added proper indentation and spacing for easier scanning
Added Missing Links:
Added direct links to all API key pages (OpenAI, Deepgram, etc.)
Added links to installation resources (pip, Firebase, etc.)
Added links to specific Google Cloud API pages
Enhanced Instructions:
Provided platform-specific instructions (Mac, Windows, Nix)
Added …
=> Update README.md - add link to the doc

.gitignore, backend/README.md, docs/docs/developer/backend/Backend_Setup.mdx
- improved backend README with more detailed setup instructions
- Added setup guide with platform-specific instructions
- Enhanced documentation with links, and explanations
**- Updated Backend_Setup.mdx with virtual environment installation options**
=> docs: backend setup documentation (+ added venv option)

app/lib/pages/conversation_detail/page.dart, app/lib/widgets/expandable_text.dart
issue: https://github.com/BasedHardware/omi/issues/1993
=> Fix external integration text cutting issue

frontend/src/app/apps/components/app-list.tsx, frontend/src/app/apps/components/developer-banner.tsx, frontend/src/app/apps/components/plugin-card/featured.tsx
=> Build your app Banner

backend/routers/transcribe.py
Reverts BasedHardware/omi#1985
=> Revert "x2 connections for the external integration"

backend/routers/pusher.py, backend/utils/apps.py
Reverts BasedHardware/omi#2032
=> Revert "Add tracing pusher 01"

.github/workflows/gcp_models.yml, backend/charts/backend-secrets/Chart.yaml, backend/charts/backend-secrets/dev_omi_backend_secrets_values.yaml, backend/charts/backend-secrets/prod_omi_backend_secrets_values.yaml, backend/charts/backend-secrets/templates/externalsecret.yaml, backend/charts/backend-secrets/templates/secretstore.yaml, backend/charts/backend-secrets/templates/serviceaccount.yaml, backend/charts/vad/.helmignore, backend/charts/vad/Chart.yaml, backend/charts/vad/dev_omi_vad_values.yaml, backend/charts/vad/prod_omi_vad_values.yaml, backend/charts/vad/templates/NOTES.txt, backend/charts/vad/templates/_helpers.tpl, backend/charts/vad/templates/deployment.yaml, backend/charts/vad/templates/hpa.yaml, backend/charts/vad/templates/ingress.yaml, backend/charts/vad/templates/service.yaml, backend/charts/vad/templates/serviceaccount.yaml, backend/charts/vad/templates/tests/test-connection.yaml, backend/charts/vad/values.yaml, backend/modal/Dockerfile, backend/modal/main.py
**Changes:**
- Helm chart for VAD
- Helm chart for Backend secrets (sync and create secrets from GCP Secret Manager using External Secret Operator)
- Add healthcheck for VAD
- Update CUDA toolkit OS to Debian 12
- Update CI/CD to deploy VAD to GKE using Helm
=> Move vad to gke

backend/charts/vad/dev_omi_vad_values.yaml, backend/charts/vad/prod_omi_vad_values.yaml
Change:
- Optimize resources usage for VAD
=> Optimize resources usage for VAD

app/lib/backend/http/api/messages.dart, app/lib/backend/http/shared.dart, app/lib/pages/chat/page.dart, app/lib/pages/chat/widgets/voice_recorder_widget.dart, app/lib/utils/audio/wav_bytes.dart, app/lib/utils/file.dart, backend/routers/chat.py, backend/utils/chat.py
=> Add voice message transcribe api

app/lib/pages/apps/widgets/action_fields_widget.dart, backend/models/facts.py, backend/models/integrations.py, backend/routers/apps.py, backend/routers/integration.py, backend/utils/llm.py, backend/utils/memories/facts.py, backend/utils/prompts.py, docs/docs/developer/apps/Import.mdx
=> Gcpbf permissive fact 2050

backend/models/integrations.py, backend/routers/integration.py, plugins/example/chatgpt/gpt_schema.example.json, plugins/example/chatgpt/main.py, plugins/example/main.py, plugins/example/templates/chatgpt/index.html
=> mAdd support get memories via integration

app/lib/backend/schema/app.dart, app/lib/pages/apps/widgets/action_fields_widget.dart, backend/models/app.py, backend/routers/apps.py, backend/routers/integration.py, docs/docs/developer/apps/Import.mdx
=> Add support new capacity read_memories, read_conversations

plugins/example/chatgpt/main.py, plugins/example/templates/chatgpt/index.html
Reverts BasedHardware/omi#2087
=> Revert "Simplify chatgpt apps by auto redirect"

docs/docs/developer/AppSetup.mdx
https://stackoverflow.com/a/70702778/10281177
=> Unify docs by importing README.MD(s)

docs/docs/developer/AppSetup.mdx
Reverts BasedHardware/omi#2086
=> Revert "Unify docs by importing README.MD(s)"

plugins/example/chatgpt/main.py, plugins/example/templates/chatgpt/index.html
Reverts BasedHardware/omi#2090
=> RR "Simplify chatgpt apps by auto redirect""

app/lib/utils/browser.dart
=> update custom tabs colors

plugins/example/chatgpt/main.py, plugins/example/templates/chatgpt/index.html
Reverts BasedHardware/omi#2114
=> Revert "RR "Simplify chatgpt apps by auto redirect"""

app/lib/utils/browser.dart
Reverts BasedHardware/omi#2115
=> Revert "Fix browser styles on iOS"

app/lib/utils/browser.dart
Reverts BasedHardware/omi#2121
=> Revert "update custom tabs colors"

.github/workflows/sync-docs.yml
closes #2112 
/claim #2112 
@beastoin @kodjima33  Here's a demo repo where I tested it, and everything is working well. Please check: https://github.com/krushnarout/omi-docs-test. Let me know your thoughts!
=> feat: sync SDK docs to README via GitHub Action

docs/docs/docs/developer/sdk/swift.mdx
=> docs: improve swift documentation

app/lib/backend/preferences.dart, app/lib/backend/schema/transcript_segment.dart, app/lib/pages/home/page.dart, app/lib/pages/onboarding/speech_profile_widget.dart, app/lib/pages/speech_profile/page.dart, app/lib/providers/speech_profile_provider.dart, app/lib/services/sockets.dart, app/lib/services/sockets/transcription_connection.dart, backend/routers/transcribe.py, backend/utils/stt/streaming.py
=> Dcegq multi lang 1892

.github/workflows/sync-docs.yml
=> feat: auto merge

omi/firmware/firmware/README.md
Fix broken link in firmware README.md to build the firmware.
=> Fix broken link in docs

web/personas-open-source/src/app/chat/page.tsx, web/personas-open-source/src/app/page.tsx, web/personas-open-source/src/components/Header.tsx, web/personas-open-source/src/components/InputArea.tsx
- added a redirect if there is ?profile parameter in url (to redirect from home page)
- changed text and urls
=> Update Omi product links and profile parameter handling

app/lib/backend/http/api/conversations.dart, app/lib/pages/capture/widgets/widgets.dart, app/lib/pages/conversation_capturing/page.dart, app/lib/pages/conversation_detail/conversation_detail_provider.dart, app/lib/pages/conversation_detail/page.dart, app/lib/pages/conversation_detail/widgets.dart, app/lib/pages/conversation_detail/widgets/summarized_apps_sheet.dart, app/lib/widgets/conversation_bottom_bar.dart, app/lib/widgets/conversation_bottom_bar/app_image.dart, app/lib/widgets/conversation_bottom_bar/tab_button.dart, app/lib/widgets/transcript.dart, backend/routers/conversations.py, backend/utils/conversations/process_conversation.py, backend/utils/llm.py
=> Revamps conversation details page

backend/models/conversation.py, backend/models/integrations.py, backend/routers/integration.py
=> Import apps changes and fixes

app/lib/pages/apps/explore_install_page.dart, app/lib/pages/apps/widgets/filter_sheet.dart, app/lib/providers/app_provider.dart
https://github.com/user-attachments/assets/f3c98fbb-f782-429d-ada8-662f3a94ccf5
=> Improve overall apps performance and fix crashing

backend/routers/transcribe.py, backend/utils/stt/streaming.py, backend/utils/translation_cache.py
=> Optimize the language detection costs by adding caching layers, Soniox language hints enabled

backend/utils/stt/streaming.py
Reverts BasedHardware/omi#2195
=> Revert "Piloting DG Nova-3"

.github/workflows/sync-docs.yml, docs/docs/docs/hardware/omiGlass.mdx
@beastoin Updated the docs with the latest changes from the PR #2216
=> docs: update to latest docs from recent PR

app/lib/pages/onboarding/wrapper.dart
Cleanup onboarding logic to consistently use fix number of tabs (to fix the incorrect tabs issue)
=> Improve onboarding flow logic

web/personas-open-source/package-lock.json, web/personas-open-source/src/app/api/enable-plugins/route.ts, web/personas-open-source/src/app/api/store-facts/route.ts, web/personas-open-source/src/app/page.tsx
to test:  Need to add .env for redis in personas folder 
REDIS_DB_HOST=your_redis_key
REDIS_DB_PORT=redis_port
REDIS_DB_PASSWORD=redis_password
After that, just run the personas using  npm run dev
provide a twitter/linkedin account => it should redirect to chatgpt that knows stuff about you 
How it should work: https://share.cleanshot.com/Y0jSdSC5
=> omi personas => import into chatgpt

web/personas-open-source/src/app/api/enable-plugins/route.ts, web/personas-open-source/src/app/api/store-facts/route.ts, web/personas-open-source/src/app/page.tsx
Reverts BasedHardware/omi#2252
yes i know im retarded
=> Revert "Revert "omi personas => import into chatgpt""

app/lib/pages/home/firmware_update.dart, backend/routers/firmware.py
https://github.com/user-attachments/assets/7e3be525-a5a4-483f-86a3-61a2ffd68834
=> cleanup and improve firmware update page ui

app/lib/pages/capture/widgets/widgets.dart, app/lib/pages/conversation_capturing/page.dart, app/lib/widgets/transcript.dart
Before:
https://github.com/user-attachments/assets/e138b828-fbdc-43d9-baf4-116c37f6cdb4
After:
https://github.com/user-attachments/assets/08769417-ddc0-486e-98ac-73c4c8a1857b
=> Live transcript overflow fix

backend/utils/llm.py
- use gpt-4.1 on the apps summarization.
=> Try openai gpt-4.1 with the summarization

backend/utils/stt/streaming.py
- the switcher in STT streaming, which prioritizing Nova-3 model.
=> Piloting nova-3, 3rd

backend/utils/stt/streaming.py
Reverts BasedHardware/omi#2324
=> Revert "Piloting nova-3, 3rd"

app/lib/backend/http/api/conversations.dart, app/lib/pages/conversation_detail/test_prompts.dart, backend/models/conversation.py, backend/routers/conversations.py, backend/utils/llm.py
Closes #1687 #1690 #2206 
https://github.com/user-attachments/assets/1415dafb-b96b-44a1-bdc2-f5b2b18792a0
=> Test prompt fix

backend/utils/stt/streaming.py
Reverts BasedHardware/omi#2325
=> Piloting nova-3 the 4th time

app/lib/backend/http/api/conversations.dart, app/lib/services/devices/omi_connection.dart
fixed: 
- https://dashboard.instabug.com/applications/tripplannerai/development/crashes/7282?filters=%7B%22date_ms%22:%7B%22shortcutLabel%22:%22Last%207%20days%22%7D,%22app_versions%22:%5B%221.0.63%20(291)%22%5D%7D
- https://dashboard.instabug.com/applications/tripplannerai/development/crashes/8441?filters=%7B%22date_ms%22:%7B%22shortcutLabel%22:%22Last%207%20days%22%7D,%22app_versions%22:%5B%221.0.63%20(291)%22%5D%7D
=> Catch exception on the device was disconnected

app/lib/pages/home/firmware_update.dart
=> improve changelog checking

backend/utils/llm.py
Improved prompt
Existing Prompt
=> Improve structured prompt for emoji

app/lib/pages/conversations/widgets/conversation_list_item.dart
=> fixed overflow error in conversation item header

app/lib/pages/apps/widgets/filter_sheet.dart, app/lib/pages/chat/page.dart, app/lib/pages/conversation_detail/widgets/summarized_apps_sheet.dart, app/lib/pages/persona/persona_profile.dart, app/lib/pages/persona/persona_provider.dart, app/lib/providers/message_provider.dart, app/lib/utils/analytics/mixpanel.dart
=> add missing mixpanel events

app/ios/Runner.xcodeproj/project.pbxproj, app/pubspec.yaml
=> upgrade deps to use latest intercom dep

app/lib/pages/apps/providers/add_app_provider.dart, app/lib/providers/app_provider.dart, app/pubspec.yaml, backend/utils/other/storage.py
=> App image cache fix

app/lib/backend/http/api/conversations.dart, app/lib/pages/action_items/action_items_page.dart, app/lib/pages/action_items/widgets/action_item_title_widget.dart, app/lib/pages/action_items/widgets/convo_action_items_group_widget.dart, app/lib/pages/action_items/widgets/edit_action_item_sheet.dart, app/lib/pages/home/page.dart, app/lib/providers/conversation_provider.dart, backend/models/conversation.py, backend/routers/conversations.py
=> Action items on home

backend/charts/backend-listen/.helmignore, backend/charts/backend-listen/Chart.yaml, backend/charts/backend-listen/dev_omi_backend_listen_values.yaml, backend/charts/backend-listen/node_pool_system_config.yaml, backend/charts/backend-listen/prod_omi_backend_listen_values.yaml, backend/charts/backend-listen/templates/NOTES.txt, backend/charts/backend-listen/templates/_helpers.tpl, backend/charts/backend-listen/templates/deployment.yaml, backend/charts/backend-listen/templates/hpa.yaml, backend/charts/backend-listen/templates/ingress.yaml, backend/charts/backend-listen/templates/service.yaml, backend/charts/backend-listen/templates/serviceaccount.yaml, backend/charts/backend-listen/templates/tests/test-connection.yaml, backend/charts/backend-listen/values.yaml, backend/charts/backend-secrets/dev_omi_backend_secrets_values.yaml, backend/charts/backend-secrets/prod_omi_backend_secrets_values.yaml
Changes:
- Add backend-listen helm chart
=> Add backend-listen helm chart

app/lib/pages/conversations/conversations_page.dart, app/lib/pages/home/page.dart, app/lib/providers/capture_provider.dart, app/lib/providers/conversation_provider.dart, app/lib/services/sockets/pure_socket.dart, backend/routers/conversations.py
=> Convos empty fixes, improving in-progress convos ux

backend/models/conversation.py
https://us5.datadoghq.com/logs?query=Failed%20to%20parse%20Structured%20from%20completion&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1747405168494&to_ts=1747577968494&live=true
=> default to other category for structured if it isn't already there in enum

app/lib/backend/preferences.dart, app/lib/pages/action_items/action_items_page.dart, app/lib/pages/action_items/widgets/action_item_title_widget.dart, app/lib/pages/apps/app_detail/app_detail.dart, app/lib/pages/conversation_detail/widgets.dart, app/lib/pages/memories/page.dart, app/lib/providers/conversation_provider.dart, backend/routers/conversations.py
=> 302 reported bug fixes

.github/workflows/gcp_backend.yml, backend/charts/backend-listen/dev_omi_backend_listen_values.yaml
Changes:
- Modify pipeline to deploy backend-listen on GKE
=> Deploy backend-listen on GKE in pipeline

backend/charts/deepgram-self-hosted/nova-3/dev_omi_values.yaml, backend/charts/deepgram-self-hosted/nova-3/prod_omi_values.yaml
Changes:
- Modify DG Engine autoscaling factor using **%GPU utilization** instead of **requestsPerPod**
=> Modify DG Engine autoscaling factor using %GPU utilization

backend/routers/firmware.py
=> Add support OMI_shell as the Omi CV 1, dealing with the flashing mistake on the new devices

backend/charts/deepgram-self-hosted/nova-3/dev_omi_values.yaml, backend/charts/deepgram-self-hosted/nova-3/prod_omi_values.yaml
Change:
- Improve autoscaling policy for Deepgram engine
=> Improve autoscaling policy for Deepgram engine

backend/utils/llm/conversation_processing.py
Update conversation processing to use llm_medium_experiment instead of llm_mini for improved transcript handling
=> Update conversation processing to use llm_medium_experiment instead of llm_mini for improved transcript handling

backend/utils/llm/conversation_processing.py
Enhance conversation processing prompts with clearer guidelines for title, overview, action items, and calendar events. Improve action item filtering and formatting for better clarity and efficiency.
=> Enhance conversation processing promptsf

backend/utils/llm/conversation_processing.py
Refine bullet formatting in conversation processing prompts for consistency and clarity
=> Refine bullet formatting in conversation processing prompts for consistency and clarity

backend/utils/llm/conversation_processing.py
Updated action items formatting. 
Updated calendar events extraction.
=> Conversation Prompt update

backend/main.py, web/frontend/next.config.mjs, web/frontend/package-lock.json, web/frontend/package.json, web/frontend/src/actions/apps/generate-description.ts, web/frontend/src/actions/apps/get-app-initialization-data.ts, web/frontend/src/actions/apps/index.ts, web/frontend/src/actions/apps/submit-app.ts, web/frontend/src/actions/apps/upload-thumbnail.ts, web/frontend/src/actions/apps/upload-thumbnails.ts, web/frontend/src/app/apps/components/developer-banner.tsx, web/frontend/src/app/create-app/page.tsx, web/frontend/src/app/my-apps/page.tsx, web/frontend/src/components/shared/app-header.tsx, web/frontend/src/components/ui/label.tsx, web/frontend/src/components/ui/progress.tsx, web/frontend/src/hooks/useAuth.ts, web/frontend/src/lib/firebase.ts
for [#2303](https://github.com/BasedHardware/omi/issues/2303)
=> feat: create app from web (#2303)

backend/charts/deepgram-self-hosted/nova-3/dev_omi_values.yaml, backend/charts/deepgram-self-hosted/nova-3/prod_omi_values.yaml
**Changes:**
- Upgrade Deepgram images to release-250505
=> Upgrade Deepgram images to release-250505

docs/docs/developer/AppSetup.mdx
Reverts BasedHardware/omi#2488
=> Revert "fix formatting in "Add fvm in automated setup scripts""

backend/utils/conversations/process_conversation.py, backend/utils/llm/conversation_processing.py
=> Regarding the conversation language on summarizing

backend/database/apps.py, backend/database/chat.py, backend/database/conversations.py, backend/database/memories.py, backend/database/users.py, backend/migration/remove_soft_deleted_documents.py, backend/models/app.py, backend/models/chat.py, backend/models/conversation.py, backend/models/integrations.py, backend/models/memories.py, backend/models/other.py, backend/routers/apps.py, backend/routers/conversations.py
- remove the soft-delete logic on the back-end.
- migration to delete all {deleted, true} docs.
deploy plan:
=> No more soft-delete on database

app/lib/providers/user_provider.dart, backend/database/chat.py, backend/database/conversations.py, backend/database/helpers.py, backend/database/memories.py, backend/models/conversation.py
**what's included ?**
- fix the issue: >statuscode.invalid_argument: The value of property "transcript_segments" is longer than 1048487 bytes.
**deploy plan:**
=> Enable transcript segments compression

web/frontend/src/hooks/useAuth.ts
- Added authError state to manage authentication errors.
- Updated signIn and signOut methods to set authError on failure without throwing.
- Improved error handling during Firebase auth initialization and cleanup.
- Ensured loading state is managed correctly during authentication processes.
=> feat:Fixing hompage redirect crashing

app/lib/pages/settings/data_privacy_page.dart, app/lib/pages/settings/widgets/data_protection_section.dart, backend/database/users.py, backend/routers/users.py
Reverts BasedHardware/omi#2585
=> Revert "Simplify data protection level; migrate all users to enhanced level -…"

omi/firmware/omi/src/battery.c
Changed R1 R2 values for accurate battery level
=> Changing R1 and R2 values

backend/charts/deepgram-self-hosted/nova-3/prod_omi_values.yaml
**Change:**
- Reduce min replicas of DG Engine to 5 for cost optimization
=> Reduce min replicas of DG Engine to 5 for cost optimization

app/lib/desktop/pages/actions/widgets/desktop_action_group.dart, app/lib/desktop/pages/apps/desktop_add_app_page.dart, app/lib/desktop/pages/apps/widgets/desktop_app_detail.dart, app/lib/desktop/pages/apps/widgets/desktop_app_metadata_widget.dart, app/lib/desktop/pages/chat/desktop_chat_page.dart, app/lib/desktop/pages/conversations/desktop_conversations_page.dart, app/lib/desktop/pages/conversations/widgets/desktop_conversation_card.dart, app/lib/desktop/pages/desktop_home_page.dart, app/lib/desktop/pages/settings/desktop_profile_page.dart, app/lib/providers/capture_provider.dart, app/lib/services/services.dart, app/lib/ui/atoms/omi_info_card.dart, app/lib/ui/atoms/omi_profile_avatar.dart, app/lib/ui/atoms/omi_section.dart, app/lib/ui/atoms/omi_settings_tile.dart, app/macos/Runner/AppDelegate.swift, app/macos/Runner/AudioManager.swift, app/macos/Runner/DebugProfile.entitlements, app/macos/Runner/MainFlutterWindow.swift, app/macos/Runner/Release.entitlements, app/macos/Runner/RunnerDebug-dev.entitlements, app/macos/Runner/RunnerDebug-prod.entitlements, app/macos/Runner/RunnerDebug.entitlements, app/macos/Runner/RunnerProfile-prod.entitlements, app/macos/Runner/RunnerProfile.entitlements, app/macos/Runner/RunnerRelease-prod.entitlements, app/macos/Runner/RunnerRelease.entitlements
=> macos recording improvements

app/lib/pages/onboarding/permissions/permissions_mobile_widget.dart
=> change location dialog text based on apple review feedback

backend/charts/deepgram-self-hosted/nova-3/prod_omi_values.yaml
**Change:**
- Increase Deepgram Engine to API ratio to save cost
=> Increase engineToApiRatio to save cost

app/lib/desktop/pages/conversations/widgets/desktop_recording_widget.dart, app/lib/providers/capture_provider.dart, app/lib/services/services.dart, app/macos/Runner/AudioManager.swift
- resolve the volume duck issue on macos
- auto reconnects on switching audio devices on macos
- simplify the audio manager on macos
deploy plan:
- deploy macos app
=> Mhmjs macos

app/lib/desktop/pages/apps/desktop_apps_page.dart, app/lib/desktop/pages/desktop_home_page.dart, app/lib/desktop/pages/memories/desktop_memories_page.dart, app/lib/desktop/pages/onboarding/screens/desktop_complete_screen.dart, app/lib/desktop/pages/onboarding/screens/desktop_language_screen.dart, app/lib/desktop/pages/onboarding/screens/desktop_name_screen.dart, app/lib/desktop/pages/onboarding/screens/desktop_permissions_screen.dart, app/lib/utils/analytics/mixpanel.dart, app/lib/utils/platform/platform_service.dart, app/pubspec.lock, app/pubspec.yaml
=> support mixpanel analytics for desktop

backend/routers/transcribe.py, backend/utils/translation.py, backend/utils/translation_cache.py
what's include ?
- costs optimization on language translation
deploy plan
- deploy backend-listen
=> Optimize the language translation costs by punctuation-based caching

app/lib/pages/conversation_detail/widgets/summarized_apps_sheet.dart, backend/database/users.py, backend/models/conversation.py, backend/models/transcript_segment.py, backend/utils/apps.py, backend/utils/conversations/process_conversation.py, backend/utils/llm/chat.py, backend/utils/llm/external_integrations.py, backend/utils/llm/followup.py, backend/utils/llm/memories.py, backend/utils/llm/trends.py, backend/utils/retrieval/graph.py, backend/utils/retrieval/rag.py
- add support recalls with the speaker on summarizing, chat, extracting user's memories.
- allow re-summarizing with the current app.
deploy plan:
demo:
https://github.com/user-attachments/assets/f215979e-fe89-495f-a790-4f1b1e3c895d
#2550
=> Speaker labling // recalls

backend/charts/deepgram-self-hosted/nova-3/prod_omi_values.yaml
Change:
- Reduce minReplicas of Deepgram engine to 4
=> Reduce minReplicas of Deepgram engine to 4

app/lib/pages/conversations/conversations_page.dart, app/lib/pages/conversations/widgets/processing_capture.dart, app/lib/pages/home/page.dart, app/lib/pages/home/widgets/battery_info_widget.dart, app/lib/providers/capture_provider.dart, app/lib/widgets/gradient_waveform.dart
mobile recording state looks like this^
device recording state looks like this^
also note the new position of the chat button and slight redesign to emphasize chat more as we want to make chat more and more usable and accessible hence the shift
=> Design fixes based on feedback from mobile-redesign

app/lib/backend/http/api/users.dart, app/lib/gen/assets.gen.dart, app/lib/main.dart, app/lib/models/user_usage.dart, app/lib/models/user_usage.g.dart, app/lib/pages/settings/page.dart, app/lib/pages/settings/settings_drawer.dart, app/lib/pages/settings/usage_page.dart, app/lib/providers/usage_provider.dart, app/pubspec.lock, app/pubspec.yaml, backend/database/user_usage.py, backend/migrations/002_populate_historical_usage.py, backend/models/user_usage.py, backend/routers/transcribe.py, backend/routers/users.py, backend/utils/analytics.py, backend/utils/conversations/process_conversation.py
what’s included?  
- user usage reports  
- option to share your Omi insights  
deploy plan:  
demo:  
https://github.com/user-attachments/assets/76cc6b50-7568-40fc-8ab6-bcd57edafc4e
=> Add support user's usages

app/lib/pages/settings/usage_page.dart, backend/migrations/002_populate_historical_usage.py
- enhance the charts on user usages, toggling the legend
- more meaningful metrics, showing it fully but not using the short form.
- fix the duration on the analytic migration
deploy plan:
=> Pwwhd users usage

app/lib/pages/apps/app_detail/app_detail.dart, app/lib/pages/apps/app_detail/widgets/add_review_widget.dart, app/lib/pages/apps/app_detail/widgets/info_card_widget.dart, app/lib/pages/chat/page.dart
one critical bottom overflow fixed on app review
error fixed on app detail page where chat button would lead to the action items page instead of opening the chat page with the selected app as the selected one
other ui fixes and enhancements throughout
=> minor ui fixes across chat and app detail pages

docs/onboarding/omi-devkit-2.mdx, docs/onboarding/omi.mdx
added button control info and light meanings to device onboarding for simplicity of users
=> Onboarding improve device

app/lib/mobile/mobile_app.dart, backend/routers/transcribe.py
what;s included?
- revive the decider widget for mobile app to fix the language missing on transcribing and translation (and, prevent the further issues)
- try to set the translation language by using the users preferences.
deploy plan:
=> Missing decider widget logics fixes

app/lib/backend/preferences.dart, app/lib/main.dart, app/lib/pages/settings/developer.dart, app/lib/providers/capture_provider.dart, app/lib/services/devices.dart, app/lib/services/sockets/transcription_connection.dart, app/lib/utils/debug_log_manager.dart, app/lib/utils/logger.dart
```
{"timestamp":"2025-08-09T07:43:18.626Z","level":"EVENT","type":"transcription_socket_connected","sample_rate":16000,"codec":"pcm16","language":"en","include_speech_profile":true}
{"timestamp":"2025-08-09T07:43:29.176Z","level":"INFO","message":"transcription_socket_stopped","extra":{"reason":"stop stream recording"}}
```
context: https://discord.com/channels/1192313062041067520/1195503933037228072/1402969104079654933
https://github.com/user-attachments/assets/31c23640-1915-490e-920c-37530debfc51
=> app logs tracking

.github/workflows/gcp_apps_js.yml, .github/workflows/gcp_backend.yml, .github/workflows/gcp_backend_pusher.yml, .github/workflows/gcp_frontend.yml, .github/workflows/gcp_plugins.yml
Change:
- Remove all Datadog wrappers in CI/CD
=> Remove all Datadog wrappers

app/lib/pages/settings/usage_page.dart
minor adjustments to enhance UI UX
background was transparent and weird of the plans sheet, fixed
closes #2783
=> enhance subscription UI/UX

backend/database/users.py, backend/routers/users.py, backend/utils/subscription.py
- more robustness in validating users subs
deploy:
=> More robustness in subs validation

backend/routers/payment.py, backend/utils/llm/notifications.py, backend/utils/notifications.py, backend/utils/subscription.py, plugins/example/main.py, plugins/example/subscription/main.py, plugins/example/templates/subscription/index.html
- notify users on subscription successfully, as a thank you letter
- omi subscription app
deploy:
=> Thank you noti on the unlimited subscription

backend/charts/backend-listen/prod_omi_backend_listen_values.yaml
**Changes:**
- Adjust backend-listen resource request and limit
- Increase minReplicas to 32 and maxReplicas to 60
=> Optimize resources usage and minReplicas to balance between cost and stability

backend/charts/deepgram-self-hosted/nova-3/prod_omi_values.yaml
**Changes:**
- Change minReplicas to 3 and maxReplicas to 10
- Increase requestPerPod to 60
=> Optimize Deepgram Engine cost

app/lib/pages/action_items/action_items_page.dart, app/lib/pages/conversation_detail/page.dart, app/lib/pages/conversations/conversations_page.dart, app/lib/providers/conversation_provider.dart, app/lib/services/app_review_service.dart
closes #2589 
Demo:
https://github.com/user-attachments/assets/833d3807-e7ba-4578-876f-76998a951d3a
https://github.com/user-attachments/assets/eb499aec-55f1-460a-996a-80ccfdee7fcf
=> feat: prompt user to review app after creating first conversation

app/lib/backend/schema/message.dart, app/lib/pages/chat/page.dart, app/lib/pages/chat/widgets/ai_message.dart, app/lib/pages/chat/widgets/markdown_message_widget.dart, app/lib/pages/chat/widgets/message_action_menu.dart, app/lib/pages/chat/widgets/user_message.dart, app/lib/providers/message_provider.dart
**what's included?** Enhance the experience of the current chat feature
- Add a new line to the chat input box when the user hits Enter on the keyboard.
- Ensure a smooth experience after hitting the send button, such as adding the new message, waiting briefly, and then scrolling to the bottom.
- Improve new message rendering, since an incomplete message (streamed chat response) might update multiple times and cause poor UX (freezing, lagging, etc.).
- Buttons such as add, mic, and send should be larger so users can tap them more easily, especially on mobile apps.
- Bring back NPS but place it into the long-press popup. We only need Not helpful feedback.
- While typing, the mic should be hidden and a clear-text button should appear in the same place. What do you think?
- Increase the …
=> Improve chat UX

app/lib/pages/capture/widgets/widgets.dart, app/lib/pages/chat/widgets/markdown_message_widget.dart, app/lib/pages/conversation_detail/page.dart, app/lib/pages/conversation_detail/widgets.dart, app/lib/pages/conversation_detail/widgets/conversation_markdown_widget.dart, app/lib/widgets/transcript.dart
closes #2771 
https://github.com/user-attachments/assets/8be5c248-32d5-4a72-bcde-930aad19370e
=> feat: search through transcript or conversation summary

app/android/app/src/main/res/values-night-v31/styles.xml, app/android/app/src/main/res/values-night/styles.xml, app/android/app/src/main/res/values-v31/styles.xml, app/android/app/src/main/res/values/styles.xml
=> opt-out of forced edge to edge on android 15 until flutter implements it

app/lib/pages/action_items/widgets/action_item_tile_widget.dart, app/lib/pages/memories/widgets/memory_item.dart
closes #2840 #2845 #2844 
https://github.com/user-attachments/assets/f7f3e0c0-6ee5-4827-b294-44c5cfed0d5a
#2845
=> fix: improve action items and memories

app/lib/pages/conversation_detail/page.dart, app/lib/pages/conversation_detail/widgets/conversation_markdown_widget.dart, app/lib/widgets/transcript.dart
fixes #2771 
- search on transcript work properly
- if the search bar is empty and someone clicks outside the search bar then it will close the search bar
- the highlighted is not hidden behind the search bar
https://github.com/user-attachments/assets/f64e974d-d8ef-44e4-baaf-37815394ff50
=> fix: transcript page search scroll

app/lib/utils/analytics/intercom.dart
=> add omi charging article

app/lib/pages/chat/page.dart
closes #2896
https://github.com/user-attachments/assets/35c0543c-ad33-4ff1-87ad-6e72bd0387a4
=> feat: gray out submit button when input field is empty

app/lib/providers/device_provider.dart, app/lib/services/devices.dart, app/lib/services/sockets.dart, app/lib/utils/mutex.dart
- reducing BLE scanning time
- improving the connection mechanism for both BLE and WebSocket
deploy
=> Reducing BLE scanning time; improving the connection mechanism for both BLE and WebSocket

app/lib/pages/home/firmware_mixin.dart, app/lib/pages/home/firmware_update.dart, app/lib/providers/device_provider.dart
#2838 
https://github.com/user-attachments/assets/ffcc592e-fce8-4ebc-9191-3444d2428e5f
=> do not show firmware update dialog while updating

codemagic.yaml
=> find upload symbols in correct dir

backend/utils/llm/chat.py, backend/utils/llm/clients.py
#2801 
Tested on prod env locally
=> use gpt-5 for rag chat

backend/utils/llm/chat.py, backend/utils/llm/clients.py
Reverts BasedHardware/omi#2921
=> Revert "use gpt-5 for rag chat"

plugins/example/notifications/hey_omi.py
=> fix notifications and improve cooldown logic in hey omi

app/lib/desktop/pages/desktop_home_page.dart, app/lib/desktop/pages/settings/desktop_about_page.dart, app/lib/desktop/pages/settings/desktop_developer_page.dart, app/lib/pages/settings/about.dart
closes #2579 #2577 
- About omi page
- Developer mode page
- fixed discord invite link
=> feat: desktop ui revamp

omiGlass/package-lock.json, omiGlass/package.json, omiGlass/sources/modules/openai.ts
This addresses issue https://github.com/BasedHardware/omi/issues/2908
Replaced Node.js `fs` module with Expo's FileSystem API to make the code compatible with React Native environments.
=> fix: Replace Node.js fs with Expo FileSystem to resolve iOS bundling error

app/lib/backend/schema/conversation.dart, app/lib/pages/action_items/widgets/action_item_tile_widget.dart, app/lib/pages/conversations/widgets/conversation_list_item.dart, app/lib/pages/memories/widgets/memory_item.dart
- clarify the message out-of-credits on the convo item, memory item, action item 
deploy:
- deploy the app
demo:  https://github.com/user-attachments/assets/02e78777-b2e8-48b0-a8ce-ac11050dab91
#2945
=> Enhance UI/UX of out of credits convos, memories, action items

backend/routers/apps.py
I was trying to create an app in my self hosted setup.
after setting up the google cloud storage buckets i still got validation issues attached below:
this PR fixes that issue.
=> Fix: App creation validation errors

app/ios/Podfile.lock, app/lib/desktop/pages/actions/widgets/desktop_action_item_form_dialog.dart, app/lib/pages/action_items/action_items_page.dart, app/lib/pages/action_items/widgets/action_item_tile_widget.dart, app/lib/providers/action_items_provider.dart, app/lib/ui/molecules/omi_confirm_dialog.dart, app/lib/ui/organisms/desktop/action_item_desktop.dart
https://github.com/user-attachments/assets/d9250139-20b9-40df-8b4a-898b1859f364
=> action items improvements

app/lib/pages/capture/widgets/widgets.dart, app/lib/pages/conversation_detail/page.dart, app/lib/pages/conversation_detail/widgets/conversation_markdown_widget.dart, app/lib/widgets/transcript.dart
=> fix: search bar bugs

app/lib/pages/memories/widgets/memory_item.dart
Reverts BasedHardware/omi#2988
---
error:
```
I/flutter (14088): │ [error] | 9:37:38 863ms |
I/flutter (14088): │ Incorrect use of ParentDataWidget.
I/flutter (14088): │ The ParentDataWidget Expanded(flex: 1) wants to apply ParentData of type FlexParentData to a RenderObject, which has been set up to accept ParentData of incompatible type StackParentData.
I/flutter (14088): │ Usually, this means that the Expanded widget has the wrong ancestor RenderObjectWidget. Typically, Expanded widgets are placed directly inside Flex widgets.
I/flutter (14088): │ The offending Expanded is currently placed inside a Stack widget.
I/flutter (14088): │ The ownership chain for the RenderObject that received the incompatible parent data was:
I/flutter (14088): │   Column ← Expanded ← Stack ← Padding ← …
```
=> Revert "feat: conversation link button in memory items"

backend/routers/transcribe.py
=> Fix the pusher loops on flushing the last pieces of audio and transcripts after the functions ended

app/lib/desktop/pages/actions/desktop_actions_page.dart, app/lib/desktop/pages/apps/desktop_apps_page.dart, app/lib/desktop/pages/chat/desktop_chat_page.dart, app/lib/desktop/pages/conversations/desktop_conversations_page.dart, app/lib/desktop/pages/memories/desktop_memories_page.dart, app/lib/desktop/pages/settings/desktop_developer_page.dart, app/lib/desktop/pages/settings/desktop_profile_page.dart
closes #2936 
https://github.com/user-attachments/assets/2a4711f2-7b65-487f-8404-1de2c8b3ed77
=> feat: enable cmd+r to reload on desktop

app/ios/Runner.xcodeproj/project.pbxproj
=> change WKCompanionAppBundleIdentifier for watch on dev flavor

app/lib/providers/capture_provider.dart
closes #3088
https://github.com/user-attachments/assets/a2e28776-bb3f-4ea8-9338-f5e557c2d026
=> fix: restore mute state on reconnect
